/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangePasswordDto,
  ForgotPasswordDto,
  LoginDto,
  RegisterDto,
  ReplaceProfileDto,
  ResendOtpDto,
  ResetPasswordDto,
  UpdateProfileDto,
  VerifyOtpDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary Register a new user account (sends OTP for email verification)
 */
export const postApiRegister = (
    registerDto: RegisterDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto, signal
    },
      );
    }
  


export const getPostApiRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiRegister>>, TError,{data: RegisterDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiRegister>>, TError,{data: RegisterDto}, TContext> => {

const mutationKey = ['postApiRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiRegister>>, {data: RegisterDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiRegister(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiRegister>>>
    export type PostApiRegisterMutationBody = RegisterDto
    export type PostApiRegisterMutationError = unknown

    /**
 * @summary Register a new user account (sends OTP for email verification)
 */
export const usePostApiRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiRegister>>, TError,{data: RegisterDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiRegister>>,
        TError,
        {data: RegisterDto},
        TContext
      > => {

      const mutationOptions = getPostApiRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Verify email with OTP code
 */
export const postApiVerifyOtp = (
    verifyOtpDto: VerifyOtpDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/verify-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyOtpDto, signal
    },
      );
    }
  


export const getPostApiVerifyOtpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVerifyOtp>>, TError,{data: VerifyOtpDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiVerifyOtp>>, TError,{data: VerifyOtpDto}, TContext> => {

const mutationKey = ['postApiVerifyOtp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiVerifyOtp>>, {data: VerifyOtpDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiVerifyOtp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiVerifyOtpMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVerifyOtp>>>
    export type PostApiVerifyOtpMutationBody = VerifyOtpDto
    export type PostApiVerifyOtpMutationError = unknown

    /**
 * @summary Verify email with OTP code
 */
export const usePostApiVerifyOtp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVerifyOtp>>, TError,{data: VerifyOtpDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiVerifyOtp>>,
        TError,
        {data: VerifyOtpDto},
        TContext
      > => {

      const mutationOptions = getPostApiVerifyOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Resend OTP to email
 */
export const postApiResendOtp = (
    resendOtpDto: ResendOtpDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/resend-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resendOtpDto, signal
    },
      );
    }
  


export const getPostApiResendOtpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiResendOtp>>, TError,{data: ResendOtpDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiResendOtp>>, TError,{data: ResendOtpDto}, TContext> => {

const mutationKey = ['postApiResendOtp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiResendOtp>>, {data: ResendOtpDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiResendOtp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiResendOtpMutationResult = NonNullable<Awaited<ReturnType<typeof postApiResendOtp>>>
    export type PostApiResendOtpMutationBody = ResendOtpDto
    export type PostApiResendOtpMutationError = unknown

    /**
 * @summary Resend OTP to email
 */
export const usePostApiResendOtp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiResendOtp>>, TError,{data: ResendOtpDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiResendOtp>>,
        TError,
        {data: ResendOtpDto},
        TContext
      > => {

      const mutationOptions = getPostApiResendOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Request a password reset link
 */
export const postApiForgotPassword = (
    forgotPasswordDto: ForgotPasswordDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordDto, signal
    },
      );
    }
  


export const getPostApiForgotPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiForgotPassword>>, TError,{data: ForgotPasswordDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiForgotPassword>>, TError,{data: ForgotPasswordDto}, TContext> => {

const mutationKey = ['postApiForgotPassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiForgotPassword>>, {data: ForgotPasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiForgotPassword(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiForgotPassword>>>
    export type PostApiForgotPasswordMutationBody = ForgotPasswordDto
    export type PostApiForgotPasswordMutationError = unknown

    /**
 * @summary Request a password reset link
 */
export const usePostApiForgotPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiForgotPassword>>, TError,{data: ForgotPasswordDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiForgotPassword>>,
        TError,
        {data: ForgotPasswordDto},
        TContext
      > => {

      const mutationOptions = getPostApiForgotPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reset password with code and new password
 */
export const putApiResetPassword = (
    resetPasswordDto: ResetPasswordDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/reset-password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordDto
    },
      );
    }
  


export const getPutApiResetPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiResetPassword>>, TError,{data: ResetPasswordDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiResetPassword>>, TError,{data: ResetPasswordDto}, TContext> => {

const mutationKey = ['putApiResetPassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiResetPassword>>, {data: ResetPasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  putApiResetPassword(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof putApiResetPassword>>>
    export type PutApiResetPasswordMutationBody = ResetPasswordDto
    export type PutApiResetPasswordMutationError = unknown

    /**
 * @summary Reset password with code and new password
 */
export const usePutApiResetPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiResetPassword>>, TError,{data: ResetPasswordDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiResetPassword>>,
        TError,
        {data: ResetPasswordDto},
        TContext
      > => {

      const mutationOptions = getPutApiResetPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Login with email or username and password
 */
export const postApiLogin = (
    loginDto: LoginDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto, signal
    },
      );
    }
  


export const getPostApiLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLogin>>, TError,{data: LoginDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiLogin>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['postApiLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLogin>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLogin>>>
    export type PostApiLoginMutationBody = LoginDto
    export type PostApiLoginMutationError = unknown

    /**
 * @summary Login with email or username and password
 */
export const usePostApiLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLogin>>, TError,{data: LoginDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLogin>>,
        TError,
        {data: LoginDto},
        TContext
      > => {

      const mutationOptions = getPostApiLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Refresh access token using refresh token (body or cookie)
 */
export const postApiRefreshToken = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/refresh`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiRefreshTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiRefreshToken>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiRefreshToken>>, TError,void, TContext> => {

const mutationKey = ['postApiRefreshToken'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiRefreshToken>>, void> = () => {
          

          return  postApiRefreshToken()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiRefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiRefreshToken>>>
    
    export type PostApiRefreshTokenMutationError = unknown

    /**
 * @summary Refresh access token using refresh token (body or cookie)
 */
export const usePostApiRefreshToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiRefreshToken>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiRefreshToken>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get current user profile
 */
export const getApiMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/me`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiMeInfiniteQueryKey = () => {
    return [
    'infinite', `/api/auth/me`
    ] as const;
    }

export const getGetApiMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }

    
export const getGetApiMeInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiMe>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMeInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({ signal }) => getApiMe(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMeInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMe>>>
export type GetApiMeInfiniteQueryError = unknown


export function useGetApiMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiMe>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user profile
 */

export function useGetApiMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMeInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get current user profile
 */
export const prefetchGetApiMeInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiMe>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiMeInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({ signal }) => getApiMe(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMe>>>
export type GetApiMeQueryError = unknown


export function useGetApiMe<TData = Awaited<ReturnType<typeof getApiMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMe<TData = Awaited<ReturnType<typeof getApiMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMe<TData = Awaited<ReturnType<typeof getApiMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user profile
 */

export function useGetApiMe<TData = Awaited<ReturnType<typeof getApiMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get current user profile
 */
export const prefetchGetApiMeQuery = async <TData = Awaited<ReturnType<typeof getApiMe>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiMeQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update current user profile (self)
 */
export const patchApiMe = (
    updateProfileDto: UpdateProfileDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileDto
    },
      );
    }
  


export const getPatchApiMeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiMe>>, TError,{data: UpdateProfileDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiMe>>, TError,{data: UpdateProfileDto}, TContext> => {

const mutationKey = ['patchApiMe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiMe>>, {data: UpdateProfileDto}> = (props) => {
          const {data} = props ?? {};

          return  patchApiMe(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiMeMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiMe>>>
    export type PatchApiMeMutationBody = UpdateProfileDto
    export type PatchApiMeMutationError = unknown

    /**
 * @summary Update current user profile (self)
 */
export const usePatchApiMe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiMe>>, TError,{data: UpdateProfileDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiMe>>,
        TError,
        {data: UpdateProfileDto},
        TContext
      > => {

      const mutationOptions = getPatchApiMeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Replace current user profile (self, full update)
 */
export const putApiMe = (
    replaceProfileDto: ReplaceProfileDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/me`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: replaceProfileDto
    },
      );
    }
  


export const getPutApiMeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiMe>>, TError,{data: ReplaceProfileDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiMe>>, TError,{data: ReplaceProfileDto}, TContext> => {

const mutationKey = ['putApiMe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiMe>>, {data: ReplaceProfileDto}> = (props) => {
          const {data} = props ?? {};

          return  putApiMe(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiMeMutationResult = NonNullable<Awaited<ReturnType<typeof putApiMe>>>
    export type PutApiMeMutationBody = ReplaceProfileDto
    export type PutApiMeMutationError = unknown

    /**
 * @summary Replace current user profile (self, full update)
 */
export const usePutApiMe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiMe>>, TError,{data: ReplaceProfileDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiMe>>,
        TError,
        {data: ReplaceProfileDto},
        TContext
      > => {

      const mutationOptions = getPutApiMeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Change current user password
 */
export const patchApiPassword = (
    changePasswordDto: ChangePasswordDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordDto
    },
      );
    }
  


export const getPatchApiPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiPassword>>, TError,{data: ChangePasswordDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiPassword>>, TError,{data: ChangePasswordDto}, TContext> => {

const mutationKey = ['patchApiPassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiPassword>>, {data: ChangePasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  patchApiPassword(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiPassword>>>
    export type PatchApiPasswordMutationBody = ChangePasswordDto
    export type PatchApiPasswordMutationError = unknown

    /**
 * @summary Change current user password
 */
export const usePatchApiPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiPassword>>, TError,{data: ChangePasswordDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiPassword>>,
        TError,
        {data: ChangePasswordDto},
        TContext
      > => {

      const mutationOptions = getPatchApiPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Logout and revoke all tokens
 */
export const postApiLogout = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiLogout>>, TError,void, TContext> => {

const mutationKey = ['postApiLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLogout>>, void> = () => {
          

          return  postApiLogout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLogout>>>
    
    export type PostApiLogoutMutationError = unknown

    /**
 * @summary Logout and revoke all tokens
 */
export const usePostApiLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Switch active tenant and get new tokens
 */
export const postApiSwitchTenant = (
    tenantId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/switch-tenant/${tenantId}`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiSwitchTenantMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSwitchTenant>>, TError,{tenantId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSwitchTenant>>, TError,{tenantId: string}, TContext> => {

const mutationKey = ['postApiSwitchTenant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSwitchTenant>>, {tenantId: string}> = (props) => {
          const {tenantId} = props ?? {};

          return  postApiSwitchTenant(tenantId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSwitchTenantMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSwitchTenant>>>
    
    export type PostApiSwitchTenantMutationError = unknown

    /**
 * @summary Switch active tenant and get new tokens
 */
export const usePostApiSwitchTenant = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSwitchTenant>>, TError,{tenantId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSwitchTenant>>,
        TError,
        {tenantId: string},
        TContext
      > => {

      const mutationOptions = getPostApiSwitchTenantMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Revoke all sessions and bump token version (force re-login everywhere)
 */
export const postApiRevokeAllTokens = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/revoke-all-tokens`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiRevokeAllTokensMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiRevokeAllTokens>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiRevokeAllTokens>>, TError,void, TContext> => {

const mutationKey = ['postApiRevokeAllTokens'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiRevokeAllTokens>>, void> = () => {
          

          return  postApiRevokeAllTokens()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiRevokeAllTokensMutationResult = NonNullable<Awaited<ReturnType<typeof postApiRevokeAllTokens>>>
    
    export type PostApiRevokeAllTokensMutationError = unknown

    /**
 * @summary Revoke all sessions and bump token version (force re-login everywhere)
 */
export const usePostApiRevokeAllTokens = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiRevokeAllTokens>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiRevokeAllTokens>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiRevokeAllTokensMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    