/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UpdateContactInfoDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary Get active contact info (public)
 */
export const getApiContactInfoPublic = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/contact-info/public`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiContactInfoPublicInfiniteQueryKey = () => {
    return [
    'infinite', `/api/contact-info/public`
    ] as const;
    }

export const getGetApiContactInfoPublicQueryKey = () => {
    return [
    `/api/contact-info/public`
    ] as const;
    }

    
export const getGetApiContactInfoPublicInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoPublic>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactInfoPublicInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactInfoPublic>>> = ({ signal }) => getApiContactInfoPublic(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactInfoPublicInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactInfoPublic>>>
export type GetApiContactInfoPublicInfiniteQueryError = unknown


export function useGetApiContactInfoPublicInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoPublic>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfoPublic>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfoPublic>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoPublicInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoPublic>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfoPublic>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfoPublic>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoPublicInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoPublic>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get active contact info (public)
 */

export function useGetApiContactInfoPublicInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoPublic>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactInfoPublicInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get active contact info (public)
 */
export const prefetchGetApiContactInfoPublicInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactInfoPublicInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiContactInfoPublicQueryOptions = <TData = Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactInfoPublicQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactInfoPublic>>> = ({ signal }) => getApiContactInfoPublic(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactInfoPublicQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactInfoPublic>>>
export type GetApiContactInfoPublicQueryError = unknown


export function useGetApiContactInfoPublic<TData = Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfoPublic>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfoPublic>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoPublic<TData = Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfoPublic>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfoPublic>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoPublic<TData = Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get active contact info (public)
 */

export function useGetApiContactInfoPublic<TData = Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactInfoPublicQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get active contact info (public)
 */
export const prefetchGetApiContactInfoPublicQuery = async <TData = Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoPublic>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactInfoPublicQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary List all contact info (admin)
 */
export const getApiContactInfo = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/contact-info`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiContactInfoInfiniteQueryKey = () => {
    return [
    'infinite', `/api/contact-info`
    ] as const;
    }

export const getGetApiContactInfoQueryKey = () => {
    return [
    `/api/contact-info`
    ] as const;
    }

    
export const getGetApiContactInfoInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfo>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactInfoInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactInfo>>> = ({ signal }) => getApiContactInfo(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactInfoInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactInfo>>>
export type GetApiContactInfoInfiniteQueryError = unknown


export function useGetApiContactInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfo>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfo>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfo>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all contact info (admin)
 */

export function useGetApiContactInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfo>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactInfoInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all contact info (admin)
 */
export const prefetchGetApiContactInfoInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiContactInfo>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactInfoInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiContactInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiContactInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactInfo>>> = ({ signal }) => getApiContactInfo(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactInfo>>>
export type GetApiContactInfoQueryError = unknown


export function useGetApiContactInfo<TData = Awaited<ReturnType<typeof getApiContactInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfo<TData = Awaited<ReturnType<typeof getApiContactInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfo<TData = Awaited<ReturnType<typeof getApiContactInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all contact info (admin)
 */

export function useGetApiContactInfo<TData = Awaited<ReturnType<typeof getApiContactInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all contact info (admin)
 */
export const prefetchGetApiContactInfoQuery = async <TData = Awaited<ReturnType<typeof getApiContactInfo>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfo>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactInfoQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Get contact info by ID (admin)
 */
export const getApiContactInfoId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/contact-info/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiContactInfoIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/contact-info/${id}`
    ] as const;
    }

export const getGetApiContactInfoIdQueryKey = (id?: string,) => {
    return [
    `/api/contact-info/${id}`
    ] as const;
    }

    
export const getGetApiContactInfoIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoId>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactInfoIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactInfoId>>> = ({ signal }) => getApiContactInfoId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactInfoIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactInfoId>>>
export type GetApiContactInfoIdInfiniteQueryError = unknown


export function useGetApiContactInfoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoId>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfoId>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfoId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfoId>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfoId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contact info by ID (admin)
 */

export function useGetApiContactInfoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactInfoId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactInfoIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get contact info by ID (admin)
 */
export const prefetchGetApiContactInfoIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiContactInfoId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactInfoIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiContactInfoIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiContactInfoId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactInfoIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactInfoId>>> = ({ signal }) => getApiContactInfoId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactInfoIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactInfoId>>>
export type GetApiContactInfoIdQueryError = unknown


export function useGetApiContactInfoId<TData = Awaited<ReturnType<typeof getApiContactInfoId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfoId>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfoId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoId<TData = Awaited<ReturnType<typeof getApiContactInfoId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactInfoId>>,
          TError,
          Awaited<ReturnType<typeof getApiContactInfoId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactInfoId<TData = Awaited<ReturnType<typeof getApiContactInfoId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contact info by ID (admin)
 */

export function useGetApiContactInfoId<TData = Awaited<ReturnType<typeof getApiContactInfoId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactInfoIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get contact info by ID (admin)
 */
export const prefetchGetApiContactInfoIdQuery = async <TData = Awaited<ReturnType<typeof getApiContactInfoId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactInfoId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactInfoIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update contact info value / isActive (admin, no create, no delete)
 */
export const patchApiContactInfoId = (
    id: string,
    updateContactInfoDto: UpdateContactInfoDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/contact-info/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateContactInfoDto
    },
      );
    }
  


export const getPatchApiContactInfoIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiContactInfoId>>, TError,{id: string;data: UpdateContactInfoDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiContactInfoId>>, TError,{id: string;data: UpdateContactInfoDto}, TContext> => {

const mutationKey = ['patchApiContactInfoId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiContactInfoId>>, {id: string;data: UpdateContactInfoDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiContactInfoId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiContactInfoIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiContactInfoId>>>
    export type PatchApiContactInfoIdMutationBody = UpdateContactInfoDto
    export type PatchApiContactInfoIdMutationError = unknown

    /**
 * @summary Update contact info value / isActive (admin, no create, no delete)
 */
export const usePatchApiContactInfoId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiContactInfoId>>, TError,{id: string;data: UpdateContactInfoDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiContactInfoId>>,
        TError,
        {id: string;data: UpdateContactInfoDto},
        TContext
      > => {

      const mutationOptions = getPatchApiContactInfoIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    