/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCustomerDto,
  CreateCustomerNeedDto,
  CreateMyNeedDto,
  GetApiCustomerNeedsParams,
  GetApiCustomersAdminParams,
  GetApiCustomersMeAppointmentsParams,
  GetApiCustomersMeContactsParams,
  GetApiCustomersMeDealsParams,
  GetApiCustomersParams,
  TransitionCustomerNeedDto,
  UpdateCustomerDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary List customers with filters
 */
export const getApiCustomers = (
    params?: GetApiCustomersParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customers`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCustomersInfiniteQueryKey = (params?: GetApiCustomersParams,) => {
    return [
    'infinite', `/api/customers`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiCustomersQueryKey = (params?: GetApiCustomersParams,) => {
    return [
    `/api/customers`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCustomersInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = unknown>(params?: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomers>>> = ({ signal }) => getApiCustomers(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomers>>>
export type GetApiCustomersInfiniteQueryError = unknown


export function useGetApiCustomersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = unknown>(
 params: undefined |  GetApiCustomersParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomers>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = unknown>(
 params?: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomers>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = unknown>(
 params?: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customers with filters
 */

export function useGetApiCustomersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = unknown>(
 params?: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List customers with filters
 */
export const prefetchGetApiCustomersInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomersQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = unknown>(params?: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomers>>> = ({ signal }) => getApiCustomers(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomers>>>
export type GetApiCustomersQueryError = unknown


export function useGetApiCustomers<TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = unknown>(
 params: undefined |  GetApiCustomersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomers>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomers<TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = unknown>(
 params?: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomers>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomers<TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = unknown>(
 params?: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customers with filters
 */

export function useGetApiCustomers<TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = unknown>(
 params?: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List customers with filters
 */
export const prefetchGetApiCustomersQuery = async <TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a customer
 */
export const postApiCustomer = (
    createCustomerDto: CreateCustomerDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomerDto, signal
    },
      );
    }
  


export const getPostApiCustomerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomer>>, TError,{data: CreateCustomerDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCustomer>>, TError,{data: CreateCustomerDto}, TContext> => {

const mutationKey = ['postApiCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCustomer>>, {data: CreateCustomerDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiCustomer(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCustomer>>>
    export type PostApiCustomerMutationBody = CreateCustomerDto
    export type PostApiCustomerMutationError = unknown

    /**
 * @summary Create a customer
 */
export const usePostApiCustomer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomer>>, TError,{data: CreateCustomerDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCustomer>>,
        TError,
        {data: CreateCustomerDto},
        TContext
      > => {

      const mutationOptions = getPostApiCustomerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List all customers for admin management
 */
export const getApiCustomersAdmin = (
    params?: GetApiCustomersAdminParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/customers/admin`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCustomersAdminInfiniteQueryKey = (params?: GetApiCustomersAdminParams,) => {
    return [
    'infinite', `/api/customers/admin`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiCustomersAdminQueryKey = (params?: GetApiCustomersAdminParams,) => {
    return [
    `/api/customers/admin`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCustomersAdminInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersAdmin>>>, TError = unknown>(params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersAdminInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersAdmin>>> = ({ signal }) => getApiCustomersAdmin(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersAdminInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersAdmin>>>
export type GetApiCustomersAdminInfiniteQueryError = unknown


export function useGetApiCustomersAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersAdmin>>>, TError = unknown>(
 params: undefined |  GetApiCustomersAdminParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersAdmin>>>, TError = unknown>(
 params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersAdmin>>>, TError = unknown>(
 params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all customers for admin management
 */

export function useGetApiCustomersAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersAdmin>>>, TError = unknown>(
 params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersAdminInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all customers for admin management
 */
export const prefetchGetApiCustomersAdminInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersAdminInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomersAdminQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError = unknown>(params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersAdminQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersAdmin>>> = ({ signal }) => getApiCustomersAdmin(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersAdminQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersAdmin>>>
export type GetApiCustomersAdminQueryError = unknown


export function useGetApiCustomersAdmin<TData = Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError = unknown>(
 params: undefined |  GetApiCustomersAdminParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersAdmin<TData = Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError = unknown>(
 params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersAdmin<TData = Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError = unknown>(
 params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all customers for admin management
 */

export function useGetApiCustomersAdmin<TData = Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError = unknown>(
 params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersAdminQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all customers for admin management
 */
export const prefetchGetApiCustomersAdminQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersAdmin>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersAdminQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Get my customer profile
 */
export const getApiCustomersMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/customers/me`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCustomersMeInfiniteQueryKey = () => {
    return [
    'infinite', `/api/customers/me`
    ] as const;
    }

export const getGetApiCustomersMeQueryKey = () => {
    return [
    `/api/customers/me`
    ] as const;
    }

    
export const getGetApiCustomersMeInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMe>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMe>>> = ({ signal }) => getApiCustomersMe(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMe>>>
export type GetApiCustomersMeInfiniteQueryError = unknown


export function useGetApiCustomersMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMe>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMe>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMe>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my customer profile
 */

export function useGetApiCustomersMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get my customer profile
 */
export const prefetchGetApiCustomersMeInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMe>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomersMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomersMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMe>>> = ({ signal }) => getApiCustomersMe(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMe>>>
export type GetApiCustomersMeQueryError = unknown


export function useGetApiCustomersMe<TData = Awaited<ReturnType<typeof getApiCustomersMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMe>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMe<TData = Awaited<ReturnType<typeof getApiCustomersMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMe>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMe<TData = Awaited<ReturnType<typeof getApiCustomersMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my customer profile
 */

export function useGetApiCustomersMe<TData = Awaited<ReturnType<typeof getApiCustomersMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get my customer profile
 */
export const prefetchGetApiCustomersMeQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMe>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMe>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary List my customer needs
 */
export const getApiCustomersMeNeeds = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/customers/me/needs`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCustomersMeNeedsInfiniteQueryKey = () => {
    return [
    'infinite', `/api/customers/me/needs`
    ] as const;
    }

export const getGetApiCustomersMeNeedsQueryKey = () => {
    return [
    `/api/customers/me/needs`
    ] as const;
    }

    
export const getGetApiCustomersMeNeedsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeNeedsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>> = ({ signal }) => getApiCustomersMeNeeds(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeNeedsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>>
export type GetApiCustomersMeNeedsInfiniteQueryError = unknown


export function useGetApiCustomersMeNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeNeeds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeNeeds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my customer needs
 */

export function useGetApiCustomersMeNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeNeedsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my customer needs
 */
export const prefetchGetApiCustomersMeNeedsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeNeedsInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomersMeNeedsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeNeedsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>> = ({ signal }) => getApiCustomersMeNeeds(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeNeedsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>>
export type GetApiCustomersMeNeedsQueryError = unknown


export function useGetApiCustomersMeNeeds<TData = Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeNeeds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeNeeds<TData = Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeNeeds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeNeeds<TData = Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my customer needs
 */

export function useGetApiCustomersMeNeeds<TData = Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeNeedsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my customer needs
 */
export const prefetchGetApiCustomersMeNeedsQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeNeeds>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeNeedsQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a need for myself (customer self-service)
 */
export const postApiCustomersMeNeeds = (
    createMyNeedDto: CreateMyNeedDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/customers/me/needs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMyNeedDto, signal
    },
      );
    }
  


export const getPostApiCustomersMeNeedsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomersMeNeeds>>, TError,{data: CreateMyNeedDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCustomersMeNeeds>>, TError,{data: CreateMyNeedDto}, TContext> => {

const mutationKey = ['postApiCustomersMeNeeds'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCustomersMeNeeds>>, {data: CreateMyNeedDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiCustomersMeNeeds(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCustomersMeNeedsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCustomersMeNeeds>>>
    export type PostApiCustomersMeNeedsMutationBody = CreateMyNeedDto
    export type PostApiCustomersMeNeedsMutationError = unknown

    /**
 * @summary Create a need for myself (customer self-service)
 */
export const usePostApiCustomersMeNeeds = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomersMeNeeds>>, TError,{data: CreateMyNeedDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCustomersMeNeeds>>,
        TError,
        {data: CreateMyNeedDto},
        TContext
      > => {

      const mutationOptions = getPostApiCustomersMeNeedsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List my deals (track transaction status)
 */
export const getApiCustomersMeDeals = (
    params?: GetApiCustomersMeDealsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/customers/me/deals`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCustomersMeDealsInfiniteQueryKey = (params?: GetApiCustomersMeDealsParams,) => {
    return [
    'infinite', `/api/customers/me/deals`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiCustomersMeDealsQueryKey = (params?: GetApiCustomersMeDealsParams,) => {
    return [
    `/api/customers/me/deals`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCustomersMeDealsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeDeals>>>, TError = unknown>(params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeDealsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMeDeals>>> = ({ signal }) => getApiCustomersMeDeals(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeDealsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMeDeals>>>
export type GetApiCustomersMeDealsInfiniteQueryError = unknown


export function useGetApiCustomersMeDealsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeDeals>>>, TError = unknown>(
 params: undefined |  GetApiCustomersMeDealsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeDeals>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeDeals>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeDealsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeDeals>>>, TError = unknown>(
 params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeDeals>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeDeals>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeDealsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeDeals>>>, TError = unknown>(
 params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my deals (track transaction status)
 */

export function useGetApiCustomersMeDealsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeDeals>>>, TError = unknown>(
 params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeDealsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my deals (track transaction status)
 */
export const prefetchGetApiCustomersMeDealsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeDealsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomersMeDealsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError = unknown>(params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeDealsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMeDeals>>> = ({ signal }) => getApiCustomersMeDeals(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeDealsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMeDeals>>>
export type GetApiCustomersMeDealsQueryError = unknown


export function useGetApiCustomersMeDeals<TData = Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError = unknown>(
 params: undefined |  GetApiCustomersMeDealsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeDeals>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeDeals>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeDeals<TData = Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError = unknown>(
 params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeDeals>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeDeals>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeDeals<TData = Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError = unknown>(
 params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my deals (track transaction status)
 */

export function useGetApiCustomersMeDeals<TData = Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError = unknown>(
 params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeDealsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my deals (track transaction status)
 */
export const prefetchGetApiCustomersMeDealsQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersMeDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeDeals>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeDealsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary List my appointments
 */
export const getApiCustomersMeAppointments = (
    params?: GetApiCustomersMeAppointmentsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/customers/me/appointments`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCustomersMeAppointmentsInfiniteQueryKey = (params?: GetApiCustomersMeAppointmentsParams,) => {
    return [
    'infinite', `/api/customers/me/appointments`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiCustomersMeAppointmentsQueryKey = (params?: GetApiCustomersMeAppointmentsParams,) => {
    return [
    `/api/customers/me/appointments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCustomersMeAppointmentsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>>, TError = unknown>(params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeAppointmentsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>> = ({ signal }) => getApiCustomersMeAppointments(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeAppointmentsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>>
export type GetApiCustomersMeAppointmentsInfiniteQueryError = unknown


export function useGetApiCustomersMeAppointmentsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>>, TError = unknown>(
 params: undefined |  GetApiCustomersMeAppointmentsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeAppointments>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeAppointments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeAppointmentsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>>, TError = unknown>(
 params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeAppointments>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeAppointments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeAppointmentsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>>, TError = unknown>(
 params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my appointments
 */

export function useGetApiCustomersMeAppointmentsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>>, TError = unknown>(
 params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeAppointmentsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my appointments
 */
export const prefetchGetApiCustomersMeAppointmentsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeAppointmentsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomersMeAppointmentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError = unknown>(params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeAppointmentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>> = ({ signal }) => getApiCustomersMeAppointments(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeAppointmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>>
export type GetApiCustomersMeAppointmentsQueryError = unknown


export function useGetApiCustomersMeAppointments<TData = Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError = unknown>(
 params: undefined |  GetApiCustomersMeAppointmentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeAppointments>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeAppointments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeAppointments<TData = Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError = unknown>(
 params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeAppointments>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeAppointments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeAppointments<TData = Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError = unknown>(
 params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my appointments
 */

export function useGetApiCustomersMeAppointments<TData = Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError = unknown>(
 params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeAppointmentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my appointments
 */
export const prefetchGetApiCustomersMeAppointmentsQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersMeAppointmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeAppointments>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeAppointmentsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary List my property contact requests
 */
export const getApiCustomersMeContacts = (
    params?: GetApiCustomersMeContactsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/customers/me/contacts`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCustomersMeContactsInfiniteQueryKey = (params?: GetApiCustomersMeContactsParams,) => {
    return [
    'infinite', `/api/customers/me/contacts`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiCustomersMeContactsQueryKey = (params?: GetApiCustomersMeContactsParams,) => {
    return [
    `/api/customers/me/contacts`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCustomersMeContactsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeContacts>>>, TError = unknown>(params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeContactsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMeContacts>>> = ({ signal }) => getApiCustomersMeContacts(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeContactsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMeContacts>>>
export type GetApiCustomersMeContactsInfiniteQueryError = unknown


export function useGetApiCustomersMeContactsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeContacts>>>, TError = unknown>(
 params: undefined |  GetApiCustomersMeContactsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeContacts>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeContacts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeContactsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeContacts>>>, TError = unknown>(
 params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeContacts>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeContacts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeContactsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeContacts>>>, TError = unknown>(
 params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my property contact requests
 */

export function useGetApiCustomersMeContactsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomersMeContacts>>>, TError = unknown>(
 params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeContactsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my property contact requests
 */
export const prefetchGetApiCustomersMeContactsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeContactsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomersMeContactsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError = unknown>(params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersMeContactsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomersMeContacts>>> = ({ signal }) => getApiCustomersMeContacts(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersMeContactsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomersMeContacts>>>
export type GetApiCustomersMeContactsQueryError = unknown


export function useGetApiCustomersMeContacts<TData = Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError = unknown>(
 params: undefined |  GetApiCustomersMeContactsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeContacts>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeContacts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeContacts<TData = Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError = unknown>(
 params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomersMeContacts>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomersMeContacts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersMeContacts<TData = Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError = unknown>(
 params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my property contact requests
 */

export function useGetApiCustomersMeContacts<TData = Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError = unknown>(
 params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersMeContactsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my property contact requests
 */
export const prefetchGetApiCustomersMeContactsQuery = async <TData = Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomersMeContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomersMeContacts>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersMeContactsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Get customer by ID
 */
export const getApiCustomerId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customers/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCustomerIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/customers/${id}`
    ] as const;
    }

export const getGetApiCustomerIdQueryKey = (id?: string,) => {
    return [
    `/api/customers/${id}`
    ] as const;
    }

    
export const getGetApiCustomerIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerId>>> = ({ signal }) => getApiCustomerId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerId>>>
export type GetApiCustomerIdInfiniteQueryError = unknown


export function useGetApiCustomerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get customer by ID
 */

export function useGetApiCustomerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get customer by ID
 */
export const prefetchGetApiCustomerIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerId>>> = ({ signal }) => getApiCustomerId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerId>>>
export type GetApiCustomerIdQueryError = unknown


export function useGetApiCustomerId<TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerId<TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerId<TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get customer by ID
 */

export function useGetApiCustomerId<TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get customer by ID
 */
export const prefetchGetApiCustomerIdQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update a customer
 */
export const patchApiCustomer = (
    id: string,
    updateCustomerDto: UpdateCustomerDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customers/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCustomerDto
    },
      );
    }
  


export const getPatchApiCustomerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCustomer>>, TError,{id: string;data: UpdateCustomerDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiCustomer>>, TError,{id: string;data: UpdateCustomerDto}, TContext> => {

const mutationKey = ['patchApiCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiCustomer>>, {id: string;data: UpdateCustomerDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiCustomer(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiCustomer>>>
    export type PatchApiCustomerMutationBody = UpdateCustomerDto
    export type PatchApiCustomerMutationError = unknown

    /**
 * @summary Update a customer
 */
export const usePatchApiCustomer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCustomer>>, TError,{id: string;data: UpdateCustomerDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiCustomer>>,
        TError,
        {id: string;data: UpdateCustomerDto},
        TContext
      > => {

      const mutationOptions = getPatchApiCustomerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Soft delete a customer
 */
export const deleteApiCustomer = (
    id: string,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customers/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiCustomerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCustomer>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCustomer>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCustomer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCustomer(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCustomer>>>
    
    export type DeleteApiCustomerMutationError = unknown

    /**
 * @summary Soft delete a customer
 */
export const useDeleteApiCustomer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCustomer>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCustomer>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiCustomerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List customer needs
 */
export const getApiCustomerNeeds = (
    params?: GetApiCustomerNeedsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customer-needs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCustomerNeedsInfiniteQueryKey = (params?: GetApiCustomerNeedsParams,) => {
    return [
    'infinite', `/api/customer-needs`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiCustomerNeedsQueryKey = (params?: GetApiCustomerNeedsParams,) => {
    return [
    `/api/customer-needs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCustomerNeedsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = unknown>(params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerNeedsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerNeeds>>> = ({ signal }) => getApiCustomerNeeds(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerNeedsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerNeeds>>>
export type GetApiCustomerNeedsInfiniteQueryError = unknown


export function useGetApiCustomerNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = unknown>(
 params: undefined |  GetApiCustomerNeedsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeeds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = unknown>(
 params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeeds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = unknown>(
 params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customer needs
 */

export function useGetApiCustomerNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = unknown>(
 params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerNeedsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List customer needs
 */
export const prefetchGetApiCustomerNeedsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerNeedsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomerNeedsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = unknown>(params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerNeedsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerNeeds>>> = ({ signal }) => getApiCustomerNeeds(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerNeedsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerNeeds>>>
export type GetApiCustomerNeedsQueryError = unknown


export function useGetApiCustomerNeeds<TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = unknown>(
 params: undefined |  GetApiCustomerNeedsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeeds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeeds<TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = unknown>(
 params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeeds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeeds<TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = unknown>(
 params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customer needs
 */

export function useGetApiCustomerNeeds<TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = unknown>(
 params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerNeedsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List customer needs
 */
export const prefetchGetApiCustomerNeedsQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerNeedsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a customer need
 */
export const postApiCustomerNeed = (
    createCustomerNeedDto: CreateCustomerNeedDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customer-needs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomerNeedDto, signal
    },
      );
    }
  


export const getPostApiCustomerNeedMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeed>>, TError,{data: CreateCustomerNeedDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeed>>, TError,{data: CreateCustomerNeedDto}, TContext> => {

const mutationKey = ['postApiCustomerNeed'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCustomerNeed>>, {data: CreateCustomerNeedDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiCustomerNeed(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCustomerNeedMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCustomerNeed>>>
    export type PostApiCustomerNeedMutationBody = CreateCustomerNeedDto
    export type PostApiCustomerNeedMutationError = unknown

    /**
 * @summary Create a customer need
 */
export const usePostApiCustomerNeed = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeed>>, TError,{data: CreateCustomerNeedDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCustomerNeed>>,
        TError,
        {data: CreateCustomerNeedDto},
        TContext
      > => {

      const mutationOptions = getPostApiCustomerNeedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get available workflow transitions for a customer need
 */
export const getApiCustomerNeedTransitions = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customer-needs/${id}/transitions`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiCustomerNeedTransitionsInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/customer-needs/${id}/transitions`
    ] as const;
    }

export const getGetApiCustomerNeedTransitionsQueryKey = (id?: string,) => {
    return [
    `/api/customer-needs/${id}/transitions`
    ] as const;
    }

    
export const getGetApiCustomerNeedTransitionsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerNeedTransitionsInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>> = ({ signal }) => getApiCustomerNeedTransitions(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerNeedTransitionsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>>
export type GetApiCustomerNeedTransitionsInfiniteQueryError = unknown


export function useGetApiCustomerNeedTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeedTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeedTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get available workflow transitions for a customer need
 */

export function useGetApiCustomerNeedTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerNeedTransitionsInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get available workflow transitions for a customer need
 */
export const prefetchGetApiCustomerNeedTransitionsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerNeedTransitionsInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCustomerNeedTransitionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerNeedTransitionsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>> = ({ signal }) => getApiCustomerNeedTransitions(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerNeedTransitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>>
export type GetApiCustomerNeedTransitionsQueryError = unknown


export function useGetApiCustomerNeedTransitions<TData = Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeedTransitions<TData = Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeedTransitions<TData = Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get available workflow transitions for a customer need
 */

export function useGetApiCustomerNeedTransitions<TData = Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerNeedTransitionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get available workflow transitions for a customer need
 */
export const prefetchGetApiCustomerNeedTransitionsQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeedTransitions>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerNeedTransitionsQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Execute a workflow transition on a customer need by transitionId
 */
export const postApiCustomerNeedTransition = (
    id: string,
    transitionCustomerNeedDto: TransitionCustomerNeedDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/customer-needs/${id}/transition`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: transitionCustomerNeedDto, signal
    },
      );
    }
  


export const getPostApiCustomerNeedTransitionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeedTransition>>, TError,{id: string;data: TransitionCustomerNeedDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeedTransition>>, TError,{id: string;data: TransitionCustomerNeedDto}, TContext> => {

const mutationKey = ['postApiCustomerNeedTransition'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCustomerNeedTransition>>, {id: string;data: TransitionCustomerNeedDto}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiCustomerNeedTransition(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCustomerNeedTransitionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCustomerNeedTransition>>>
    export type PostApiCustomerNeedTransitionMutationBody = TransitionCustomerNeedDto
    export type PostApiCustomerNeedTransitionMutationError = unknown

    /**
 * @summary Execute a workflow transition on a customer need by transitionId
 */
export const usePostApiCustomerNeedTransition = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeedTransition>>, TError,{id: string;data: TransitionCustomerNeedDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCustomerNeedTransition>>,
        TError,
        {id: string;data: TransitionCustomerNeedDto},
        TContext
      > => {

      const mutationOptions = getPostApiCustomerNeedTransitionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    