/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddFavoriteDto,
  GetApiFavoritesParams
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary List my favorite properties
 */
export const getApiFavorites = (
    params?: GetApiFavoritesParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/favorites`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiFavoritesInfiniteQueryKey = (params?: GetApiFavoritesParams,) => {
    return [
    'infinite', `/api/favorites`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiFavoritesQueryKey = (params?: GetApiFavoritesParams,) => {
    return [
    `/api/favorites`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiFavoritesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiFavorites>>>, TError = unknown>(params?: GetApiFavoritesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFavoritesInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFavorites>>> = ({ signal }) => getApiFavorites(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFavoritesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFavorites>>>
export type GetApiFavoritesInfiniteQueryError = unknown


export function useGetApiFavoritesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFavorites>>>, TError = unknown>(
 params: undefined |  GetApiFavoritesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiFavorites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFavoritesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFavorites>>>, TError = unknown>(
 params?: GetApiFavoritesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiFavorites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFavoritesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFavorites>>>, TError = unknown>(
 params?: GetApiFavoritesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my favorite properties
 */

export function useGetApiFavoritesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFavorites>>>, TError = unknown>(
 params?: GetApiFavoritesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFavoritesInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my favorite properties
 */
export const prefetchGetApiFavoritesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiFavorites>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiFavoritesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFavoritesInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiFavoritesQueryOptions = <TData = Awaited<ReturnType<typeof getApiFavorites>>, TError = unknown>(params?: GetApiFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFavoritesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFavorites>>> = ({ signal }) => getApiFavorites(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFavoritesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFavorites>>>
export type GetApiFavoritesQueryError = unknown


export function useGetApiFavorites<TData = Awaited<ReturnType<typeof getApiFavorites>>, TError = unknown>(
 params: undefined |  GetApiFavoritesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiFavorites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFavorites<TData = Awaited<ReturnType<typeof getApiFavorites>>, TError = unknown>(
 params?: GetApiFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiFavorites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFavorites<TData = Awaited<ReturnType<typeof getApiFavorites>>, TError = unknown>(
 params?: GetApiFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my favorite properties
 */

export function useGetApiFavorites<TData = Awaited<ReturnType<typeof getApiFavorites>>, TError = unknown>(
 params?: GetApiFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFavoritesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my favorite properties
 */
export const prefetchGetApiFavoritesQuery = async <TData = Awaited<ReturnType<typeof getApiFavorites>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavorites>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFavoritesQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Save a property to favorites
 */
export const postApiFavorites = (
    addFavoriteDto: AddFavoriteDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/favorites`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addFavoriteDto, signal
    },
      );
    }
  


export const getPostApiFavoritesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFavorites>>, TError,{data: AddFavoriteDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiFavorites>>, TError,{data: AddFavoriteDto}, TContext> => {

const mutationKey = ['postApiFavorites'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiFavorites>>, {data: AddFavoriteDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiFavorites(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiFavoritesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiFavorites>>>
    export type PostApiFavoritesMutationBody = AddFavoriteDto
    export type PostApiFavoritesMutationError = unknown

    /**
 * @summary Save a property to favorites
 */
export const usePostApiFavorites = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFavorites>>, TError,{data: AddFavoriteDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiFavorites>>,
        TError,
        {data: AddFavoriteDto},
        TContext
      > => {

      const mutationOptions = getPostApiFavoritesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List my favorited property ids (for heart state)
 */
export const getApiFavoriteIds = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/favorites/ids`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiFavoriteIdsInfiniteQueryKey = () => {
    return [
    'infinite', `/api/favorites/ids`
    ] as const;
    }

export const getGetApiFavoriteIdsQueryKey = () => {
    return [
    `/api/favorites/ids`
    ] as const;
    }

    
export const getGetApiFavoriteIdsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiFavoriteIds>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFavoriteIdsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFavoriteIds>>> = ({ signal }) => getApiFavoriteIds(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFavoriteIdsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFavoriteIds>>>
export type GetApiFavoriteIdsInfiniteQueryError = unknown


export function useGetApiFavoriteIdsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFavoriteIds>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFavoriteIds>>,
          TError,
          Awaited<ReturnType<typeof getApiFavoriteIds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFavoriteIdsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFavoriteIds>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFavoriteIds>>,
          TError,
          Awaited<ReturnType<typeof getApiFavoriteIds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFavoriteIdsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFavoriteIds>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my favorited property ids (for heart state)
 */

export function useGetApiFavoriteIdsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFavoriteIds>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFavoriteIdsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my favorited property ids (for heart state)
 */
export const prefetchGetApiFavoriteIdsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiFavoriteIds>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFavoriteIdsInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiFavoriteIdsQueryOptions = <TData = Awaited<ReturnType<typeof getApiFavoriteIds>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFavoriteIdsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFavoriteIds>>> = ({ signal }) => getApiFavoriteIds(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFavoriteIdsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFavoriteIds>>>
export type GetApiFavoriteIdsQueryError = unknown


export function useGetApiFavoriteIds<TData = Awaited<ReturnType<typeof getApiFavoriteIds>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFavoriteIds>>,
          TError,
          Awaited<ReturnType<typeof getApiFavoriteIds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFavoriteIds<TData = Awaited<ReturnType<typeof getApiFavoriteIds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFavoriteIds>>,
          TError,
          Awaited<ReturnType<typeof getApiFavoriteIds>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFavoriteIds<TData = Awaited<ReturnType<typeof getApiFavoriteIds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my favorited property ids (for heart state)
 */

export function useGetApiFavoriteIds<TData = Awaited<ReturnType<typeof getApiFavoriteIds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFavoriteIdsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List my favorited property ids (for heart state)
 */
export const prefetchGetApiFavoriteIdsQuery = async <TData = Awaited<ReturnType<typeof getApiFavoriteIds>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFavoriteIds>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFavoriteIdsQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Remove a property from favorites
 */
export const deleteApiFavorite = (
    propertyId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/favorites/${propertyId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiFavoriteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiFavorite>>, TError,{propertyId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiFavorite>>, TError,{propertyId: string}, TContext> => {

const mutationKey = ['deleteApiFavorite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiFavorite>>, {propertyId: string}> = (props) => {
          const {propertyId} = props ?? {};

          return  deleteApiFavorite(propertyId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiFavorite>>>
    
    export type DeleteApiFavoriteMutationError = unknown

    /**
 * @summary Remove a property from favorites
 */
export const useDeleteApiFavorite = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiFavorite>>, TError,{propertyId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiFavorite>>,
        TError,
        {propertyId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    