/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignLeadDto,
  CreateLeadActivityDto,
  CreateLeadDto,
  GetApiLeadsAdminParams,
  GetApiLeadsParams,
  GetApiLeadsPoolParams,
  TransitionLeadDto,
  UpdateLeadDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary List leads with filters
 */
export const getApiLeads = (
    params?: GetApiLeadsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiLeadsInfiniteQueryKey = (params?: GetApiLeadsParams,) => {
    return [
    'infinite', `/api/leads`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiLeadsQueryKey = (params?: GetApiLeadsParams,) => {
    return [
    `/api/leads`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiLeadsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = unknown>(params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeads>>> = ({ signal }) => getApiLeads(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeads>>>
export type GetApiLeadsInfiniteQueryError = unknown


export function useGetApiLeadsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = unknown>(
 params: undefined |  GetApiLeadsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeads>>,
          TError,
          Awaited<ReturnType<typeof getApiLeads>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = unknown>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeads>>,
          TError,
          Awaited<ReturnType<typeof getApiLeads>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = unknown>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List leads with filters
 */

export function useGetApiLeadsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = unknown>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List leads with filters
 */
export const prefetchGetApiLeadsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeads>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiLeadsQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeads>>, TError = unknown>(params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeads>>> = ({ signal }) => getApiLeads(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeads>>>
export type GetApiLeadsQueryError = unknown


export function useGetApiLeads<TData = Awaited<ReturnType<typeof getApiLeads>>, TError = unknown>(
 params: undefined |  GetApiLeadsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeads>>,
          TError,
          Awaited<ReturnType<typeof getApiLeads>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeads<TData = Awaited<ReturnType<typeof getApiLeads>>, TError = unknown>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeads>>,
          TError,
          Awaited<ReturnType<typeof getApiLeads>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeads<TData = Awaited<ReturnType<typeof getApiLeads>>, TError = unknown>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List leads with filters
 */

export function useGetApiLeads<TData = Awaited<ReturnType<typeof getApiLeads>>, TError = unknown>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List leads with filters
 */
export const prefetchGetApiLeadsQuery = async <TData = Awaited<ReturnType<typeof getApiLeads>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a lead
 */
export const postApiLead = (
    createLeadDto: CreateLeadDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLeadDto, signal
    },
      );
    }
  


export const getPostApiLeadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLead>>, TError,{data: CreateLeadDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiLead>>, TError,{data: CreateLeadDto}, TContext> => {

const mutationKey = ['postApiLead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLead>>, {data: CreateLeadDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiLead(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiLeadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLead>>>
    export type PostApiLeadMutationBody = CreateLeadDto
    export type PostApiLeadMutationError = unknown

    /**
 * @summary Create a lead
 */
export const usePostApiLead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLead>>, TError,{data: CreateLeadDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLead>>,
        TError,
        {data: CreateLeadDto},
        TContext
      > => {

      const mutationOptions = getPostApiLeadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List all leads for admin management
 */
export const getApiLeadsAdmin = (
    params?: GetApiLeadsAdminParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/leads/admin`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiLeadsAdminInfiniteQueryKey = (params?: GetApiLeadsAdminParams,) => {
    return [
    'infinite', `/api/leads/admin`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiLeadsAdminQueryKey = (params?: GetApiLeadsAdminParams,) => {
    return [
    `/api/leads/admin`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiLeadsAdminInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsAdmin>>>, TError = unknown>(params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadsAdminInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadsAdmin>>> = ({ signal }) => getApiLeadsAdmin(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadsAdminInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadsAdmin>>>
export type GetApiLeadsAdminInfiniteQueryError = unknown


export function useGetApiLeadsAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsAdmin>>>, TError = unknown>(
 params: undefined |  GetApiLeadsAdminParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadsAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadsAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsAdmin>>>, TError = unknown>(
 params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadsAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadsAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsAdmin>>>, TError = unknown>(
 params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all leads for admin management
 */

export function useGetApiLeadsAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsAdmin>>>, TError = unknown>(
 params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadsAdminInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all leads for admin management
 */
export const prefetchGetApiLeadsAdminInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadsAdminInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiLeadsAdminQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError = unknown>(params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadsAdminQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadsAdmin>>> = ({ signal }) => getApiLeadsAdmin(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadsAdminQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadsAdmin>>>
export type GetApiLeadsAdminQueryError = unknown


export function useGetApiLeadsAdmin<TData = Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError = unknown>(
 params: undefined |  GetApiLeadsAdminParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadsAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadsAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsAdmin<TData = Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError = unknown>(
 params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadsAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadsAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsAdmin<TData = Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError = unknown>(
 params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all leads for admin management
 */

export function useGetApiLeadsAdmin<TData = Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError = unknown>(
 params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadsAdminQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all leads for admin management
 */
export const prefetchGetApiLeadsAdminQuery = async <TData = Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiLeadsAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsAdmin>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadsAdminQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary List unassigned leads (lead pool)
 */
export const getApiLeadsPool = (
    params?: GetApiLeadsPoolParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/leads/pool`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiLeadsPoolInfiniteQueryKey = (params?: GetApiLeadsPoolParams,) => {
    return [
    'infinite', `/api/leads/pool`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiLeadsPoolQueryKey = (params?: GetApiLeadsPoolParams,) => {
    return [
    `/api/leads/pool`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiLeadsPoolInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsPool>>>, TError = unknown>(params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadsPoolInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadsPool>>> = ({ signal }) => getApiLeadsPool(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadsPoolInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadsPool>>>
export type GetApiLeadsPoolInfiniteQueryError = unknown


export function useGetApiLeadsPoolInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsPool>>>, TError = unknown>(
 params: undefined |  GetApiLeadsPoolParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadsPool>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadsPool>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsPoolInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsPool>>>, TError = unknown>(
 params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadsPool>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadsPool>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsPoolInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsPool>>>, TError = unknown>(
 params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List unassigned leads (lead pool)
 */

export function useGetApiLeadsPoolInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadsPool>>>, TError = unknown>(
 params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadsPoolInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List unassigned leads (lead pool)
 */
export const prefetchGetApiLeadsPoolInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeadsPool>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadsPoolInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiLeadsPoolQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeadsPool>>, TError = unknown>(params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadsPoolQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadsPool>>> = ({ signal }) => getApiLeadsPool(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadsPoolQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadsPool>>>
export type GetApiLeadsPoolQueryError = unknown


export function useGetApiLeadsPool<TData = Awaited<ReturnType<typeof getApiLeadsPool>>, TError = unknown>(
 params: undefined |  GetApiLeadsPoolParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadsPool>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadsPool>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsPool<TData = Awaited<ReturnType<typeof getApiLeadsPool>>, TError = unknown>(
 params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadsPool>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadsPool>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsPool<TData = Awaited<ReturnType<typeof getApiLeadsPool>>, TError = unknown>(
 params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List unassigned leads (lead pool)
 */

export function useGetApiLeadsPool<TData = Awaited<ReturnType<typeof getApiLeadsPool>>, TError = unknown>(
 params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadsPoolQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List unassigned leads (lead pool)
 */
export const prefetchGetApiLeadsPoolQuery = async <TData = Awaited<ReturnType<typeof getApiLeadsPool>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiLeadsPoolParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadsPool>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadsPoolQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Sales claims a lead from the pool
 */
export const postApiLeadClaim = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/leads/${id}/claim`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiLeadClaimMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadClaim>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiLeadClaim>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiLeadClaim'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLeadClaim>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiLeadClaim(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiLeadClaimMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLeadClaim>>>
    
    export type PostApiLeadClaimMutationError = unknown

    /**
 * @summary Sales claims a lead from the pool
 */
export const usePostApiLeadClaim = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadClaim>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLeadClaim>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiLeadClaimMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Assign a pool lead to a sales or team
 */
export const postApiLeadAssign = (
    id: string,
    assignLeadDto: AssignLeadDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/leads/${id}/assign`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignLeadDto, signal
    },
      );
    }
  


export const getPostApiLeadAssignMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadAssign>>, TError,{id: string;data: AssignLeadDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiLeadAssign>>, TError,{id: string;data: AssignLeadDto}, TContext> => {

const mutationKey = ['postApiLeadAssign'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLeadAssign>>, {id: string;data: AssignLeadDto}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiLeadAssign(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiLeadAssignMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLeadAssign>>>
    export type PostApiLeadAssignMutationBody = AssignLeadDto
    export type PostApiLeadAssignMutationError = unknown

    /**
 * @summary Assign a pool lead to a sales or team
 */
export const usePostApiLeadAssign = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadAssign>>, TError,{id: string;data: AssignLeadDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLeadAssign>>,
        TError,
        {id: string;data: AssignLeadDto},
        TContext
      > => {

      const mutationOptions = getPostApiLeadAssignMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get lead by ID
 */
export const getApiLeadId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiLeadIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/leads/${id}`
    ] as const;
    }

export const getGetApiLeadIdQueryKey = (id?: string,) => {
    return [
    `/api/leads/${id}`
    ] as const;
    }

    
export const getGetApiLeadIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadId>>> = ({ signal }) => getApiLeadId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadId>>>
export type GetApiLeadIdInfiniteQueryError = unknown


export function useGetApiLeadIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadId>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadId>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get lead by ID
 */

export function useGetApiLeadIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get lead by ID
 */
export const prefetchGetApiLeadIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiLeadIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadId>>> = ({ signal }) => getApiLeadId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadId>>>
export type GetApiLeadIdQueryError = unknown


export function useGetApiLeadId<TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadId>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadId<TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadId>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadId<TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get lead by ID
 */

export function useGetApiLeadId<TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get lead by ID
 */
export const prefetchGetApiLeadIdQuery = async <TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update a lead
 */
export const patchApiLead = (
    id: string,
    updateLeadDto: UpdateLeadDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateLeadDto
    },
      );
    }
  


export const getPatchApiLeadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiLead>>, TError,{id: string;data: UpdateLeadDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiLead>>, TError,{id: string;data: UpdateLeadDto}, TContext> => {

const mutationKey = ['patchApiLead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiLead>>, {id: string;data: UpdateLeadDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiLead(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiLeadMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiLead>>>
    export type PatchApiLeadMutationBody = UpdateLeadDto
    export type PatchApiLeadMutationError = unknown

    /**
 * @summary Update a lead
 */
export const usePatchApiLead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiLead>>, TError,{id: string;data: UpdateLeadDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiLead>>,
        TError,
        {id: string;data: UpdateLeadDto},
        TContext
      > => {

      const mutationOptions = getPatchApiLeadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Soft delete a lead
 */
export const deleteApiLead = (
    id: string,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiLeadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiLead>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiLead>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiLead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiLead>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiLead(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiLeadMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiLead>>>
    
    export type DeleteApiLeadMutationError = unknown

    /**
 * @summary Soft delete a lead
 */
export const useDeleteApiLead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiLead>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiLead>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiLeadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get available workflow transitions for a lead
 */
export const getApiLeadTransitions = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads/${id}/transitions`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiLeadTransitionsInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/leads/${id}/transitions`
    ] as const;
    }

export const getGetApiLeadTransitionsQueryKey = (id?: string,) => {
    return [
    `/api/leads/${id}/transitions`
    ] as const;
    }

    
export const getGetApiLeadTransitionsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadTransitions>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadTransitionsInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadTransitions>>> = ({ signal }) => getApiLeadTransitions(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadTransitionsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadTransitions>>>
export type GetApiLeadTransitionsInfiniteQueryError = unknown


export function useGetApiLeadTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadTransitions>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get available workflow transitions for a lead
 */

export function useGetApiLeadTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadTransitionsInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get available workflow transitions for a lead
 */
export const prefetchGetApiLeadTransitionsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeadTransitions>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadTransitionsInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiLeadTransitionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeadTransitions>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadTransitionsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadTransitions>>> = ({ signal }) => getApiLeadTransitions(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadTransitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadTransitions>>>
export type GetApiLeadTransitionsQueryError = unknown


export function useGetApiLeadTransitions<TData = Awaited<ReturnType<typeof getApiLeadTransitions>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadTransitions<TData = Awaited<ReturnType<typeof getApiLeadTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadTransitions<TData = Awaited<ReturnType<typeof getApiLeadTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get available workflow transitions for a lead
 */

export function useGetApiLeadTransitions<TData = Awaited<ReturnType<typeof getApiLeadTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadTransitionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get available workflow transitions for a lead
 */
export const prefetchGetApiLeadTransitionsQuery = async <TData = Awaited<ReturnType<typeof getApiLeadTransitions>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadTransitions>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadTransitionsQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Execute a workflow transition on a lead by transitionId
 */
export const postApiLeadTransition = (
    id: string,
    transitionLeadDto: TransitionLeadDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads/${id}/transition`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: transitionLeadDto, signal
    },
      );
    }
  


export const getPostApiLeadTransitionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadTransition>>, TError,{id: string;data: TransitionLeadDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiLeadTransition>>, TError,{id: string;data: TransitionLeadDto}, TContext> => {

const mutationKey = ['postApiLeadTransition'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLeadTransition>>, {id: string;data: TransitionLeadDto}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiLeadTransition(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiLeadTransitionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLeadTransition>>>
    export type PostApiLeadTransitionMutationBody = TransitionLeadDto
    export type PostApiLeadTransitionMutationError = unknown

    /**
 * @summary Execute a workflow transition on a lead by transitionId
 */
export const usePostApiLeadTransition = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadTransition>>, TError,{id: string;data: TransitionLeadDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLeadTransition>>,
        TError,
        {id: string;data: TransitionLeadDto},
        TContext
      > => {

      const mutationOptions = getPostApiLeadTransitionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List activities for a lead
 */
export const getApiLeadActivities = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads/${id}/activities`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiLeadActivitiesInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/leads/${id}/activities`
    ] as const;
    }

export const getGetApiLeadActivitiesQueryKey = (id?: string,) => {
    return [
    `/api/leads/${id}/activities`
    ] as const;
    }

    
export const getGetApiLeadActivitiesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadActivitiesInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadActivities>>> = ({ signal }) => getApiLeadActivities(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadActivitiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadActivities>>>
export type GetApiLeadActivitiesInfiniteQueryError = unknown


export function useGetApiLeadActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List activities for a lead
 */

export function useGetApiLeadActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadActivitiesInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List activities for a lead
 */
export const prefetchGetApiLeadActivitiesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadActivitiesInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiLeadActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadActivitiesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadActivities>>> = ({ signal }) => getApiLeadActivities(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadActivities>>>
export type GetApiLeadActivitiesQueryError = unknown


export function useGetApiLeadActivities<TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadActivities<TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadActivities<TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List activities for a lead
 */

export function useGetApiLeadActivities<TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadActivitiesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List activities for a lead
 */
export const prefetchGetApiLeadActivitiesQuery = async <TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadActivitiesQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Add an activity to a lead
 */
export const postApiLeadActivity = (
    id: string,
    createLeadActivityDto: CreateLeadActivityDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/leads/${id}/activities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLeadActivityDto, signal
    },
      );
    }
  


export const getPostApiLeadActivityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadActivity>>, TError,{id: string;data: CreateLeadActivityDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiLeadActivity>>, TError,{id: string;data: CreateLeadActivityDto}, TContext> => {

const mutationKey = ['postApiLeadActivity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLeadActivity>>, {id: string;data: CreateLeadActivityDto}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiLeadActivity(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiLeadActivityMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLeadActivity>>>
    export type PostApiLeadActivityMutationBody = CreateLeadActivityDto
    export type PostApiLeadActivityMutationError = unknown

    /**
 * @summary Add an activity to a lead
 */
export const usePostApiLeadActivity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadActivity>>, TError,{id: string;data: CreateLeadActivityDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLeadActivity>>,
        TError,
        {id: string;data: CreateLeadActivityDto},
        TContext
      > => {

      const mutationOptions = getPostApiLeadActivityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    