/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddTeamMemberDto,
  CreateTeamDto,
  GetApiTeamsParams,
  UpdateTeamDto,
  UpdateTeamMemberDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary List teams in tenant
 */
export const getApiTeams = (
    params?: GetApiTeamsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/teams`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiTeamsInfiniteQueryKey = (params?: GetApiTeamsParams,) => {
    return [
    'infinite', `/api/teams`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiTeamsQueryKey = (params?: GetApiTeamsParams,) => {
    return [
    `/api/teams`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiTeamsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTeams>>>, TError = unknown>(params?: GetApiTeamsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTeamsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTeams>>> = ({ signal }) => getApiTeams(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTeamsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTeams>>>
export type GetApiTeamsInfiniteQueryError = unknown


export function useGetApiTeamsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeams>>>, TError = unknown>(
 params: undefined |  GetApiTeamsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeams>>,
          TError,
          Awaited<ReturnType<typeof getApiTeams>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeams>>>, TError = unknown>(
 params?: GetApiTeamsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeams>>,
          TError,
          Awaited<ReturnType<typeof getApiTeams>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeams>>>, TError = unknown>(
 params?: GetApiTeamsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List teams in tenant
 */

export function useGetApiTeamsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeams>>>, TError = unknown>(
 params?: GetApiTeamsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTeamsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List teams in tenant
 */
export const prefetchGetApiTeamsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTeams>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiTeamsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTeamsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTeamsQueryOptions = <TData = Awaited<ReturnType<typeof getApiTeams>>, TError = unknown>(params?: GetApiTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTeamsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTeams>>> = ({ signal }) => getApiTeams(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTeamsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTeams>>>
export type GetApiTeamsQueryError = unknown


export function useGetApiTeams<TData = Awaited<ReturnType<typeof getApiTeams>>, TError = unknown>(
 params: undefined |  GetApiTeamsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeams>>,
          TError,
          Awaited<ReturnType<typeof getApiTeams>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeams<TData = Awaited<ReturnType<typeof getApiTeams>>, TError = unknown>(
 params?: GetApiTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeams>>,
          TError,
          Awaited<ReturnType<typeof getApiTeams>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeams<TData = Awaited<ReturnType<typeof getApiTeams>>, TError = unknown>(
 params?: GetApiTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List teams in tenant
 */

export function useGetApiTeams<TData = Awaited<ReturnType<typeof getApiTeams>>, TError = unknown>(
 params?: GetApiTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTeamsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List teams in tenant
 */
export const prefetchGetApiTeamsQuery = async <TData = Awaited<ReturnType<typeof getApiTeams>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeams>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTeamsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a team
 */
export const postApiTeams = (
    createTeamDto: CreateTeamDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/teams`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTeamDto, signal
    },
      );
    }
  


export const getPostApiTeamsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTeams>>, TError,{data: CreateTeamDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiTeams>>, TError,{data: CreateTeamDto}, TContext> => {

const mutationKey = ['postApiTeams'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTeams>>, {data: CreateTeamDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiTeams(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiTeamsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTeams>>>
    export type PostApiTeamsMutationBody = CreateTeamDto
    export type PostApiTeamsMutationError = unknown

    /**
 * @summary Create a team
 */
export const usePostApiTeams = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTeams>>, TError,{data: CreateTeamDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTeams>>,
        TError,
        {data: CreateTeamDto},
        TContext
      > => {

      const mutationOptions = getPostApiTeamsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get team detail with members
 */
export const getApiTeam = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/teams/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiTeamInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/teams/${id}`
    ] as const;
    }

export const getGetApiTeamQueryKey = (id?: string,) => {
    return [
    `/api/teams/${id}`
    ] as const;
    }

    
export const getGetApiTeamInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTeam>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTeamInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTeam>>> = ({ signal }) => getApiTeam(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTeamInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTeam>>>
export type GetApiTeamInfiniteQueryError = unknown


export function useGetApiTeamInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeam>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeam>>,
          TError,
          Awaited<ReturnType<typeof getApiTeam>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeam>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeam>>,
          TError,
          Awaited<ReturnType<typeof getApiTeam>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeam>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get team detail with members
 */

export function useGetApiTeamInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeam>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTeamInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get team detail with members
 */
export const prefetchGetApiTeamInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTeam>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTeamInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTeamQueryOptions = <TData = Awaited<ReturnType<typeof getApiTeam>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTeamQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTeam>>> = ({ signal }) => getApiTeam(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTeamQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTeam>>>
export type GetApiTeamQueryError = unknown


export function useGetApiTeam<TData = Awaited<ReturnType<typeof getApiTeam>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeam>>,
          TError,
          Awaited<ReturnType<typeof getApiTeam>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeam<TData = Awaited<ReturnType<typeof getApiTeam>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeam>>,
          TError,
          Awaited<ReturnType<typeof getApiTeam>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeam<TData = Awaited<ReturnType<typeof getApiTeam>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get team detail with members
 */

export function useGetApiTeam<TData = Awaited<ReturnType<typeof getApiTeam>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTeamQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get team detail with members
 */
export const prefetchGetApiTeamQuery = async <TData = Awaited<ReturnType<typeof getApiTeam>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeam>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTeamQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update team (name, leader, status)
 */
export const patchApiTeam = (
    id: string,
    updateTeamDto: UpdateTeamDto,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/teams/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTeamDto
    },
      );
    }
  


export const getPatchApiTeamMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTeam>>, TError,{id: string;data: UpdateTeamDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiTeam>>, TError,{id: string;data: UpdateTeamDto}, TContext> => {

const mutationKey = ['patchApiTeam'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiTeam>>, {id: string;data: UpdateTeamDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiTeam(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiTeamMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiTeam>>>
    export type PatchApiTeamMutationBody = UpdateTeamDto
    export type PatchApiTeamMutationError = unknown

    /**
 * @summary Update team (name, leader, status)
 */
export const usePatchApiTeam = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTeam>>, TError,{id: string;data: UpdateTeamDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiTeam>>,
        TError,
        {id: string;data: UpdateTeamDto},
        TContext
      > => {

      const mutationOptions = getPatchApiTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Soft delete a team
 */
export const deleteApiTeam = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/teams/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiTeamMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTeam>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiTeam>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiTeam'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiTeam>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiTeam(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiTeamMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiTeam>>>
    
    export type DeleteApiTeamMutationError = unknown

    /**
 * @summary Soft delete a team
 */
export const useDeleteApiTeam = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTeam>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiTeam>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get team member detail (profile, roles, stats)
 */
export const getApiTeamMember = (
    id: string,
    userId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/teams/${id}/members/${userId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiTeamMemberInfiniteQueryKey = (id?: string,
    userId?: string,) => {
    return [
    'infinite', `/api/teams/${id}/members/${userId}`
    ] as const;
    }

export const getGetApiTeamMemberQueryKey = (id?: string,
    userId?: string,) => {
    return [
    `/api/teams/${id}/members/${userId}`
    ] as const;
    }

    
export const getGetApiTeamMemberInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamMember>>>, TError = unknown>(id: string,
    userId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTeamMemberInfiniteQueryKey(id,userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTeamMember>>> = ({ signal }) => getApiTeamMember(id,userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id && userId),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTeamMemberInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTeamMember>>>
export type GetApiTeamMemberInfiniteQueryError = unknown


export function useGetApiTeamMemberInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamMember>>>, TError = unknown>(
 id: string,
    userId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeamMember>>,
          TError,
          Awaited<ReturnType<typeof getApiTeamMember>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamMemberInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamMember>>>, TError = unknown>(
 id: string,
    userId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeamMember>>,
          TError,
          Awaited<ReturnType<typeof getApiTeamMember>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamMemberInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamMember>>>, TError = unknown>(
 id: string,
    userId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get team member detail (profile, roles, stats)
 */

export function useGetApiTeamMemberInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamMember>>>, TError = unknown>(
 id: string,
    userId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTeamMemberInfiniteQueryOptions(id,userId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get team member detail (profile, roles, stats)
 */
export const prefetchGetApiTeamMemberInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTeamMember>>, TError = unknown>(
 queryClient: QueryClient, id: string,
    userId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTeamMemberInfiniteQueryOptions(id,userId,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTeamMemberQueryOptions = <TData = Awaited<ReturnType<typeof getApiTeamMember>>, TError = unknown>(id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTeamMemberQueryKey(id,userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTeamMember>>> = ({ signal }) => getApiTeamMember(id,userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id && userId),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTeamMemberQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTeamMember>>>
export type GetApiTeamMemberQueryError = unknown


export function useGetApiTeamMember<TData = Awaited<ReturnType<typeof getApiTeamMember>>, TError = unknown>(
 id: string,
    userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeamMember>>,
          TError,
          Awaited<ReturnType<typeof getApiTeamMember>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamMember<TData = Awaited<ReturnType<typeof getApiTeamMember>>, TError = unknown>(
 id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeamMember>>,
          TError,
          Awaited<ReturnType<typeof getApiTeamMember>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamMember<TData = Awaited<ReturnType<typeof getApiTeamMember>>, TError = unknown>(
 id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get team member detail (profile, roles, stats)
 */

export function useGetApiTeamMember<TData = Awaited<ReturnType<typeof getApiTeamMember>>, TError = unknown>(
 id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTeamMemberQueryOptions(id,userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get team member detail (profile, roles, stats)
 */
export const prefetchGetApiTeamMemberQuery = async <TData = Awaited<ReturnType<typeof getApiTeamMember>>, TError = unknown>(
 queryClient: QueryClient, id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamMember>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTeamMemberQueryOptions(id,userId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update team member (status)
 */
export const patchApiTeamMember = (
    id: string,
    userId: string,
    updateTeamMemberDto: UpdateTeamMemberDto,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/teams/${id}/members/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTeamMemberDto
    },
      );
    }
  


export const getPatchApiTeamMemberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTeamMember>>, TError,{id: string;userId: string;data: UpdateTeamMemberDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiTeamMember>>, TError,{id: string;userId: string;data: UpdateTeamMemberDto}, TContext> => {

const mutationKey = ['patchApiTeamMember'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiTeamMember>>, {id: string;userId: string;data: UpdateTeamMemberDto}> = (props) => {
          const {id,userId,data} = props ?? {};

          return  patchApiTeamMember(id,userId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiTeamMemberMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiTeamMember>>>
    export type PatchApiTeamMemberMutationBody = UpdateTeamMemberDto
    export type PatchApiTeamMemberMutationError = unknown

    /**
 * @summary Update team member (status)
 */
export const usePatchApiTeamMember = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTeamMember>>, TError,{id: string;userId: string;data: UpdateTeamMemberDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiTeamMember>>,
        TError,
        {id: string;userId: string;data: UpdateTeamMemberDto},
        TContext
      > => {

      const mutationOptions = getPatchApiTeamMemberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove member from team
 */
export const deleteApiTeamMember = (
    id: string,
    userId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/teams/${id}/members/${userId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiTeamMemberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTeamMember>>, TError,{id: string;userId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiTeamMember>>, TError,{id: string;userId: string}, TContext> => {

const mutationKey = ['deleteApiTeamMember'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiTeamMember>>, {id: string;userId: string}> = (props) => {
          const {id,userId} = props ?? {};

          return  deleteApiTeamMember(id,userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiTeamMemberMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiTeamMember>>>
    
    export type DeleteApiTeamMemberMutationError = unknown

    /**
 * @summary Remove member from team
 */
export const useDeleteApiTeamMember = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiTeamMember>>, TError,{id: string;userId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiTeamMember>>,
        TError,
        {id: string;userId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiTeamMemberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Add a member to team
 */
export const postApiTeamMember = (
    id: string,
    addTeamMemberDto: AddTeamMemberDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/teams/${id}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addTeamMemberDto, signal
    },
      );
    }
  


export const getPostApiTeamMemberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTeamMember>>, TError,{id: string;data: AddTeamMemberDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiTeamMember>>, TError,{id: string;data: AddTeamMemberDto}, TContext> => {

const mutationKey = ['postApiTeamMember'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTeamMember>>, {id: string;data: AddTeamMemberDto}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiTeamMember(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiTeamMemberMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTeamMember>>>
    export type PostApiTeamMemberMutationBody = AddTeamMemberDto
    export type PostApiTeamMemberMutationError = unknown

    /**
 * @summary Add a member to team
 */
export const usePostApiTeamMember = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTeamMember>>, TError,{id: string;data: AddTeamMemberDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTeamMember>>,
        TError,
        {id: string;data: AddTeamMemberDto},
        TContext
      > => {

      const mutationOptions = getPostApiTeamMemberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    