/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTenantDto,
  GetApiTenantsParams,
  ToggleTenantFeatureDto,
  UpsertTenantSettingDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary List all tenants (super admin)
 */
export const getApiTenants = (
    params?: GetApiTenantsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiTenantsInfiniteQueryKey = (params?: GetApiTenantsParams,) => {
    return [
    'infinite', `/api/tenants`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiTenantsQueryKey = (params?: GetApiTenantsParams,) => {
    return [
    `/api/tenants`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiTenantsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTenants>>>, TError = unknown>(params?: GetApiTenantsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenants>>> = ({ signal }) => getApiTenants(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenants>>>
export type GetApiTenantsInfiniteQueryError = unknown


export function useGetApiTenantsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenants>>>, TError = unknown>(
 params: undefined |  GetApiTenantsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenants>>,
          TError,
          Awaited<ReturnType<typeof getApiTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenants>>>, TError = unknown>(
 params?: GetApiTenantsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenants>>,
          TError,
          Awaited<ReturnType<typeof getApiTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenants>>>, TError = unknown>(
 params?: GetApiTenantsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all tenants (super admin)
 */

export function useGetApiTenantsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenants>>>, TError = unknown>(
 params?: GetApiTenantsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all tenants (super admin)
 */
export const prefetchGetApiTenantsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTenants>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiTenantsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTenantsQueryOptions = <TData = Awaited<ReturnType<typeof getApiTenants>>, TError = unknown>(params?: GetApiTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenants>>> = ({ signal }) => getApiTenants(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenants>>>
export type GetApiTenantsQueryError = unknown


export function useGetApiTenants<TData = Awaited<ReturnType<typeof getApiTenants>>, TError = unknown>(
 params: undefined |  GetApiTenantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenants>>,
          TError,
          Awaited<ReturnType<typeof getApiTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenants<TData = Awaited<ReturnType<typeof getApiTenants>>, TError = unknown>(
 params?: GetApiTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenants>>,
          TError,
          Awaited<ReturnType<typeof getApiTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenants<TData = Awaited<ReturnType<typeof getApiTenants>>, TError = unknown>(
 params?: GetApiTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all tenants (super admin)
 */

export function useGetApiTenants<TData = Awaited<ReturnType<typeof getApiTenants>>, TError = unknown>(
 params?: GetApiTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all tenants (super admin)
 */
export const prefetchGetApiTenantsQuery = async <TData = Awaited<ReturnType<typeof getApiTenants>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenants>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a new tenant (agency/developer)
 */
export const postApiTenant = (
    createTenantDto: CreateTenantDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTenantDto, signal
    },
      );
    }
  


export const getPostApiTenantMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTenant>>, TError,{data: CreateTenantDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiTenant>>, TError,{data: CreateTenantDto}, TContext> => {

const mutationKey = ['postApiTenant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTenant>>, {data: CreateTenantDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiTenant(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiTenantMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTenant>>>
    export type PostApiTenantMutationBody = CreateTenantDto
    export type PostApiTenantMutationError = unknown

    /**
 * @summary Create a new tenant (agency/developer)
 */
export const usePostApiTenant = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTenant>>, TError,{data: CreateTenantDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTenant>>,
        TError,
        {data: CreateTenantDto},
        TContext
      > => {

      const mutationOptions = getPostApiTenantMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get tenant by ID
 */
export const getApiTenantId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiTenantIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/tenants/${id}`
    ] as const;
    }

export const getGetApiTenantIdQueryKey = (id?: string,) => {
    return [
    `/api/tenants/${id}`
    ] as const;
    }

    
export const getGetApiTenantIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantId>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantId>>> = ({ signal }) => getApiTenantId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantId>>>
export type GetApiTenantIdInfiniteQueryError = unknown


export function useGetApiTenantIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantId>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantId>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantId>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get tenant by ID
 */

export function useGetApiTenantIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get tenant by ID
 */
export const prefetchGetApiTenantIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTenantId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTenantIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiTenantId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantId>>> = ({ signal }) => getApiTenantId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantId>>>
export type GetApiTenantIdQueryError = unknown


export function useGetApiTenantId<TData = Awaited<ReturnType<typeof getApiTenantId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantId>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantId<TData = Awaited<ReturnType<typeof getApiTenantId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantId>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantId<TData = Awaited<ReturnType<typeof getApiTenantId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get tenant by ID
 */

export function useGetApiTenantId<TData = Awaited<ReturnType<typeof getApiTenantId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get tenant by ID
 */
export const prefetchGetApiTenantIdQuery = async <TData = Awaited<ReturnType<typeof getApiTenantId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Resolve tenant by code (public, for branding)
 */
export const getApiTenantByCode = (
    code: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants/code/${code}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiTenantByCodeInfiniteQueryKey = (code?: string,) => {
    return [
    'infinite', `/api/tenants/code/${code}`
    ] as const;
    }

export const getGetApiTenantByCodeQueryKey = (code?: string,) => {
    return [
    `/api/tenants/code/${code}`
    ] as const;
    }

    
export const getGetApiTenantByCodeInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByCode>>>, TError = unknown>(code: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantByCodeInfiniteQueryKey(code);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantByCode>>> = ({ signal }) => getApiTenantByCode(code, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(code),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantByCodeInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantByCode>>>
export type GetApiTenantByCodeInfiniteQueryError = unknown


export function useGetApiTenantByCodeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByCode>>>, TError = unknown>(
 code: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantByCode>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantByCode>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantByCodeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByCode>>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantByCode>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantByCode>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantByCodeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByCode>>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve tenant by code (public, for branding)
 */

export function useGetApiTenantByCodeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByCode>>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantByCodeInfiniteQueryOptions(code,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Resolve tenant by code (public, for branding)
 */
export const prefetchGetApiTenantByCodeInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTenantByCode>>, TError = unknown>(
 queryClient: QueryClient, code: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantByCodeInfiniteQueryOptions(code,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTenantByCodeQueryOptions = <TData = Awaited<ReturnType<typeof getApiTenantByCode>>, TError = unknown>(code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantByCodeQueryKey(code);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantByCode>>> = ({ signal }) => getApiTenantByCode(code, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(code),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantByCodeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantByCode>>>
export type GetApiTenantByCodeQueryError = unknown


export function useGetApiTenantByCode<TData = Awaited<ReturnType<typeof getApiTenantByCode>>, TError = unknown>(
 code: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantByCode>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantByCode>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantByCode<TData = Awaited<ReturnType<typeof getApiTenantByCode>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantByCode>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantByCode>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantByCode<TData = Awaited<ReturnType<typeof getApiTenantByCode>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve tenant by code (public, for branding)
 */

export function useGetApiTenantByCode<TData = Awaited<ReturnType<typeof getApiTenantByCode>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantByCodeQueryOptions(code,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Resolve tenant by code (public, for branding)
 */
export const prefetchGetApiTenantByCodeQuery = async <TData = Awaited<ReturnType<typeof getApiTenantByCode>>, TError = unknown>(
 queryClient: QueryClient, code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByCode>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantByCodeQueryOptions(code,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Resolve tenant by domain
 */
export const getApiTenantByDomain = (
    domain: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants/domain/${domain}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiTenantByDomainInfiniteQueryKey = (domain?: string,) => {
    return [
    'infinite', `/api/tenants/domain/${domain}`
    ] as const;
    }

export const getGetApiTenantByDomainQueryKey = (domain?: string,) => {
    return [
    `/api/tenants/domain/${domain}`
    ] as const;
    }

    
export const getGetApiTenantByDomainInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByDomain>>>, TError = unknown>(domain: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantByDomainInfiniteQueryKey(domain);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantByDomain>>> = ({ signal }) => getApiTenantByDomain(domain, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(domain),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantByDomainInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantByDomain>>>
export type GetApiTenantByDomainInfiniteQueryError = unknown


export function useGetApiTenantByDomainInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByDomain>>>, TError = unknown>(
 domain: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantByDomain>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantByDomain>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantByDomainInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByDomain>>>, TError = unknown>(
 domain: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantByDomain>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantByDomain>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantByDomainInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByDomain>>>, TError = unknown>(
 domain: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve tenant by domain
 */

export function useGetApiTenantByDomainInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantByDomain>>>, TError = unknown>(
 domain: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantByDomainInfiniteQueryOptions(domain,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Resolve tenant by domain
 */
export const prefetchGetApiTenantByDomainInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTenantByDomain>>, TError = unknown>(
 queryClient: QueryClient, domain: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantByDomainInfiniteQueryOptions(domain,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTenantByDomainQueryOptions = <TData = Awaited<ReturnType<typeof getApiTenantByDomain>>, TError = unknown>(domain: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantByDomainQueryKey(domain);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantByDomain>>> = ({ signal }) => getApiTenantByDomain(domain, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(domain),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantByDomainQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantByDomain>>>
export type GetApiTenantByDomainQueryError = unknown


export function useGetApiTenantByDomain<TData = Awaited<ReturnType<typeof getApiTenantByDomain>>, TError = unknown>(
 domain: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantByDomain>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantByDomain>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantByDomain<TData = Awaited<ReturnType<typeof getApiTenantByDomain>>, TError = unknown>(
 domain: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantByDomain>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantByDomain>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantByDomain<TData = Awaited<ReturnType<typeof getApiTenantByDomain>>, TError = unknown>(
 domain: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve tenant by domain
 */

export function useGetApiTenantByDomain<TData = Awaited<ReturnType<typeof getApiTenantByDomain>>, TError = unknown>(
 domain: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantByDomainQueryOptions(domain,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Resolve tenant by domain
 */
export const prefetchGetApiTenantByDomainQuery = async <TData = Awaited<ReturnType<typeof getApiTenantByDomain>>, TError = unknown>(
 queryClient: QueryClient, domain: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantByDomain>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantByDomainQueryOptions(domain,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Get tenant settings
 */
export const getApiTenantSettings = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants/${id}/settings`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiTenantSettingsInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/tenants/${id}/settings`
    ] as const;
    }

export const getGetApiTenantSettingsQueryKey = (id?: string,) => {
    return [
    `/api/tenants/${id}/settings`
    ] as const;
    }

    
export const getGetApiTenantSettingsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantSettings>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantSettingsInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantSettings>>> = ({ signal }) => getApiTenantSettings(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantSettingsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantSettings>>>
export type GetApiTenantSettingsInfiniteQueryError = unknown


export function useGetApiTenantSettingsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantSettings>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantSettingsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantSettings>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantSettingsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantSettings>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get tenant settings
 */

export function useGetApiTenantSettingsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantSettings>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantSettingsInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get tenant settings
 */
export const prefetchGetApiTenantSettingsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTenantSettings>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantSettingsInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTenantSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getApiTenantSettings>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantSettingsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantSettings>>> = ({ signal }) => getApiTenantSettings(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantSettings>>>
export type GetApiTenantSettingsQueryError = unknown


export function useGetApiTenantSettings<TData = Awaited<ReturnType<typeof getApiTenantSettings>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantSettings<TData = Awaited<ReturnType<typeof getApiTenantSettings>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantSettings<TData = Awaited<ReturnType<typeof getApiTenantSettings>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get tenant settings
 */

export function useGetApiTenantSettings<TData = Awaited<ReturnType<typeof getApiTenantSettings>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantSettingsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get tenant settings
 */
export const prefetchGetApiTenantSettingsQuery = async <TData = Awaited<ReturnType<typeof getApiTenantSettings>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantSettings>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantSettingsQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Upsert a tenant setting
 */
export const patchApiTenantSetting = (
    id: string,
    upsertTenantSettingDto: UpsertTenantSettingDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants/${id}/settings`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: upsertTenantSettingDto
    },
      );
    }
  


export const getPatchApiTenantSettingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTenantSetting>>, TError,{id: string;data: UpsertTenantSettingDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiTenantSetting>>, TError,{id: string;data: UpsertTenantSettingDto}, TContext> => {

const mutationKey = ['patchApiTenantSetting'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiTenantSetting>>, {id: string;data: UpsertTenantSettingDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiTenantSetting(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiTenantSettingMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiTenantSetting>>>
    export type PatchApiTenantSettingMutationBody = UpsertTenantSettingDto
    export type PatchApiTenantSettingMutationError = unknown

    /**
 * @summary Upsert a tenant setting
 */
export const usePatchApiTenantSetting = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTenantSetting>>, TError,{id: string;data: UpsertTenantSettingDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiTenantSetting>>,
        TError,
        {id: string;data: UpsertTenantSettingDto},
        TContext
      > => {

      const mutationOptions = getPatchApiTenantSettingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get tenant feature flags
 */
export const getApiTenantFeatures = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants/${id}/features`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiTenantFeaturesInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/tenants/${id}/features`
    ] as const;
    }

export const getGetApiTenantFeaturesQueryKey = (id?: string,) => {
    return [
    `/api/tenants/${id}/features`
    ] as const;
    }

    
export const getGetApiTenantFeaturesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantFeatures>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantFeaturesInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantFeatures>>> = ({ signal }) => getApiTenantFeatures(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantFeaturesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantFeatures>>>
export type GetApiTenantFeaturesInfiniteQueryError = unknown


export function useGetApiTenantFeaturesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantFeatures>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantFeatures>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantFeatures>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantFeaturesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantFeatures>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantFeatures>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantFeatures>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantFeaturesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantFeatures>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get tenant feature flags
 */

export function useGetApiTenantFeaturesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTenantFeatures>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantFeaturesInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get tenant feature flags
 */
export const prefetchGetApiTenantFeaturesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTenantFeatures>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantFeaturesInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTenantFeaturesQueryOptions = <TData = Awaited<ReturnType<typeof getApiTenantFeatures>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTenantFeaturesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTenantFeatures>>> = ({ signal }) => getApiTenantFeatures(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTenantFeaturesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTenantFeatures>>>
export type GetApiTenantFeaturesQueryError = unknown


export function useGetApiTenantFeatures<TData = Awaited<ReturnType<typeof getApiTenantFeatures>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantFeatures>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantFeatures>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantFeatures<TData = Awaited<ReturnType<typeof getApiTenantFeatures>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTenantFeatures>>,
          TError,
          Awaited<ReturnType<typeof getApiTenantFeatures>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTenantFeatures<TData = Awaited<ReturnType<typeof getApiTenantFeatures>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get tenant feature flags
 */

export function useGetApiTenantFeatures<TData = Awaited<ReturnType<typeof getApiTenantFeatures>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTenantFeaturesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get tenant feature flags
 */
export const prefetchGetApiTenantFeaturesQuery = async <TData = Awaited<ReturnType<typeof getApiTenantFeatures>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTenantFeatures>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTenantFeaturesQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Toggle a tenant feature flag
 */
export const patchApiTenantFeature = (
    id: string,
    toggleTenantFeatureDto: ToggleTenantFeatureDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/tenants/${id}/features`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: toggleTenantFeatureDto
    },
      );
    }
  


export const getPatchApiTenantFeatureMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTenantFeature>>, TError,{id: string;data: ToggleTenantFeatureDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiTenantFeature>>, TError,{id: string;data: ToggleTenantFeatureDto}, TContext> => {

const mutationKey = ['patchApiTenantFeature'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiTenantFeature>>, {id: string;data: ToggleTenantFeatureDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiTenantFeature(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiTenantFeatureMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiTenantFeature>>>
    export type PatchApiTenantFeatureMutationBody = ToggleTenantFeatureDto
    export type PatchApiTenantFeatureMutationError = unknown

    /**
 * @summary Toggle a tenant feature flag
 */
export const usePatchApiTenantFeature = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiTenantFeature>>, TError,{id: string;data: ToggleTenantFeatureDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiTenantFeature>>,
        TError,
        {id: string;data: ToggleTenantFeatureDto},
        TContext
      > => {

      const mutationOptions = getPatchApiTenantFeatureMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    