/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateWorkflowDto,
  GetApiWorkflowEntityStatusFieldsParams,
  GetApiWorkflowsParams,
  UpdateWorkflowDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary Get status fields for an entity type (for workflow state mapping)
 */
export const getApiWorkflowEntityStatusFields = (
    params: GetApiWorkflowEntityStatusFieldsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/workflows/entity-status-fields`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiWorkflowEntityStatusFieldsInfiniteQueryKey = (params?: GetApiWorkflowEntityStatusFieldsParams,) => {
    return [
    'infinite', `/api/workflows/entity-status-fields`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiWorkflowEntityStatusFieldsQueryKey = (params?: GetApiWorkflowEntityStatusFieldsParams,) => {
    return [
    `/api/workflows/entity-status-fields`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiWorkflowEntityStatusFieldsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>>, TError = unknown>(params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowEntityStatusFieldsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>> = ({ signal }) => getApiWorkflowEntityStatusFields(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowEntityStatusFieldsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>>
export type GetApiWorkflowEntityStatusFieldsInfiniteQueryError = unknown


export function useGetApiWorkflowEntityStatusFieldsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>>, TError = unknown>(
 params: GetApiWorkflowEntityStatusFieldsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowEntityStatusFieldsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>>, TError = unknown>(
 params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowEntityStatusFieldsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>>, TError = unknown>(
 params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get status fields for an entity type (for workflow state mapping)
 */

export function useGetApiWorkflowEntityStatusFieldsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>>, TError = unknown>(
 params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowEntityStatusFieldsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get status fields for an entity type (for workflow state mapping)
 */
export const prefetchGetApiWorkflowEntityStatusFieldsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError = unknown>(
 queryClient: QueryClient, params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowEntityStatusFieldsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiWorkflowEntityStatusFieldsQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError = unknown>(params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowEntityStatusFieldsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>> = ({ signal }) => getApiWorkflowEntityStatusFields(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowEntityStatusFieldsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>>
export type GetApiWorkflowEntityStatusFieldsQueryError = unknown


export function useGetApiWorkflowEntityStatusFields<TData = Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError = unknown>(
 params: GetApiWorkflowEntityStatusFieldsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowEntityStatusFields<TData = Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError = unknown>(
 params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowEntityStatusFields<TData = Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError = unknown>(
 params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get status fields for an entity type (for workflow state mapping)
 */

export function useGetApiWorkflowEntityStatusFields<TData = Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError = unknown>(
 params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowEntityStatusFieldsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get status fields for an entity type (for workflow state mapping)
 */
export const prefetchGetApiWorkflowEntityStatusFieldsQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError = unknown>(
 queryClient: QueryClient, params: GetApiWorkflowEntityStatusFieldsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowEntityStatusFields>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowEntityStatusFieldsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary List workflow definitions
 */
export const getApiWorkflows = (
    params?: GetApiWorkflowsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/workflows`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiWorkflowsInfiniteQueryKey = (params?: GetApiWorkflowsParams,) => {
    return [
    'infinite', `/api/workflows`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiWorkflowsQueryKey = (params?: GetApiWorkflowsParams,) => {
    return [
    `/api/workflows`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiWorkflowsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = unknown>(params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflows>>> = ({ signal }) => getApiWorkflows(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflows>>>
export type GetApiWorkflowsInfiniteQueryError = unknown


export function useGetApiWorkflowsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = unknown>(
 params: undefined |  GetApiWorkflowsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflows>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = unknown>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflows>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = unknown>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List workflow definitions
 */

export function useGetApiWorkflowsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = unknown>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List workflow definitions
 */
export const prefetchGetApiWorkflowsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiWorkflowsQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = unknown>(params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflows>>> = ({ signal }) => getApiWorkflows(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflows>>>
export type GetApiWorkflowsQueryError = unknown


export function useGetApiWorkflows<TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = unknown>(
 params: undefined |  GetApiWorkflowsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflows>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflows<TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = unknown>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflows>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflows<TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = unknown>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List workflow definitions
 */

export function useGetApiWorkflows<TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = unknown>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List workflow definitions
 */
export const prefetchGetApiWorkflowsQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a workflow definition with states and transitions
 */
export const postApiWorkflow = (
    createWorkflowDto: CreateWorkflowDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/workflows`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkflowDto, signal
    },
      );
    }
  


export const getPostApiWorkflowMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkflow>>, TError,{data: CreateWorkflowDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkflow>>, TError,{data: CreateWorkflowDto}, TContext> => {

const mutationKey = ['postApiWorkflow'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkflow>>, {data: CreateWorkflowDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiWorkflow(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkflow>>>
    export type PostApiWorkflowMutationBody = CreateWorkflowDto
    export type PostApiWorkflowMutationError = unknown

    /**
 * @summary Create a workflow definition with states and transitions
 */
export const usePostApiWorkflow = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkflow>>, TError,{data: CreateWorkflowDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkflow>>,
        TError,
        {data: CreateWorkflowDto},
        TContext
      > => {

      const mutationOptions = getPostApiWorkflowMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get workflow definition by ID
 */
export const getApiWorkflowId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/workflows/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiWorkflowIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/workflows/${id}`
    ] as const;
    }

export const getGetApiWorkflowIdQueryKey = (id?: string,) => {
    return [
    `/api/workflows/${id}`
    ] as const;
    }

    
export const getGetApiWorkflowIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowId>>> = ({ signal }) => getApiWorkflowId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowId>>>
export type GetApiWorkflowIdInfiniteQueryError = unknown


export function useGetApiWorkflowIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get workflow definition by ID
 */

export function useGetApiWorkflowIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get workflow definition by ID
 */
export const prefetchGetApiWorkflowIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiWorkflowIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowId>>> = ({ signal }) => getApiWorkflowId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowId>>>
export type GetApiWorkflowIdQueryError = unknown


export function useGetApiWorkflowId<TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowId<TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowId<TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get workflow definition by ID
 */

export function useGetApiWorkflowId<TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get workflow definition by ID
 */
export const prefetchGetApiWorkflowIdQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update a workflow definition
 */
export const putApiWorkflowId = (
    id: string,
    updateWorkflowDto: UpdateWorkflowDto,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/workflows/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkflowDto
    },
      );
    }
  


export const getPutApiWorkflowIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWorkflowId>>, TError,{id: string;data: UpdateWorkflowDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiWorkflowId>>, TError,{id: string;data: UpdateWorkflowDto}, TContext> => {

const mutationKey = ['putApiWorkflowId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiWorkflowId>>, {id: string;data: UpdateWorkflowDto}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiWorkflowId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiWorkflowIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiWorkflowId>>>
    export type PutApiWorkflowIdMutationBody = UpdateWorkflowDto
    export type PutApiWorkflowIdMutationError = unknown

    /**
 * @summary Update a workflow definition
 */
export const usePutApiWorkflowId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWorkflowId>>, TError,{id: string;data: UpdateWorkflowDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiWorkflowId>>,
        TError,
        {id: string;data: UpdateWorkflowDto},
        TContext
      > => {

      const mutationOptions = getPutApiWorkflowIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a workflow definition
 */
export const deleteApiWorkflowId = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/workflows/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiWorkflowIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkflowId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkflowId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiWorkflowId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiWorkflowId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiWorkflowId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiWorkflowIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiWorkflowId>>>
    
    export type DeleteApiWorkflowIdMutationError = unknown

    /**
 * @summary Delete a workflow definition
 */
export const useDeleteApiWorkflowId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkflowId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiWorkflowId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiWorkflowIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get states of a workflow definition
 */
export const getApiWorkflowIdStates = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/workflows/${id}/states`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiWorkflowIdStatesInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/workflows/${id}/states`
    ] as const;
    }

export const getGetApiWorkflowIdStatesQueryKey = (id?: string,) => {
    return [
    `/api/workflows/${id}/states`
    ] as const;
    }

    
export const getGetApiWorkflowIdStatesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdStates>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowIdStatesInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowIdStates>>> = ({ signal }) => getApiWorkflowIdStates(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowIdStatesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowIdStates>>>
export type GetApiWorkflowIdStatesInfiniteQueryError = unknown


export function useGetApiWorkflowIdStatesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdStates>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowIdStates>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowIdStates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdStatesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdStates>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowIdStates>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowIdStates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdStatesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdStates>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get states of a workflow definition
 */

export function useGetApiWorkflowIdStatesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdStates>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowIdStatesInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get states of a workflow definition
 */
export const prefetchGetApiWorkflowIdStatesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowIdStatesInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiWorkflowIdStatesQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowIdStatesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowIdStates>>> = ({ signal }) => getApiWorkflowIdStates(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowIdStatesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowIdStates>>>
export type GetApiWorkflowIdStatesQueryError = unknown


export function useGetApiWorkflowIdStates<TData = Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowIdStates>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowIdStates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdStates<TData = Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowIdStates>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowIdStates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdStates<TData = Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get states of a workflow definition
 */

export function useGetApiWorkflowIdStates<TData = Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowIdStatesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get states of a workflow definition
 */
export const prefetchGetApiWorkflowIdStatesQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdStates>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowIdStatesQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Get transitions of a workflow definition
 */
export const getApiWorkflowIdTransitions = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/workflows/${id}/transitions`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiWorkflowIdTransitionsInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/workflows/${id}/transitions`
    ] as const;
    }

export const getGetApiWorkflowIdTransitionsQueryKey = (id?: string,) => {
    return [
    `/api/workflows/${id}/transitions`
    ] as const;
    }

    
export const getGetApiWorkflowIdTransitionsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowIdTransitionsInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>> = ({ signal }) => getApiWorkflowIdTransitions(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowIdTransitionsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>>
export type GetApiWorkflowIdTransitionsInfiniteQueryError = unknown


export function useGetApiWorkflowIdTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get transitions of a workflow definition
 */

export function useGetApiWorkflowIdTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowIdTransitionsInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get transitions of a workflow definition
 */
export const prefetchGetApiWorkflowIdTransitionsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowIdTransitionsInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiWorkflowIdTransitionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowIdTransitionsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>> = ({ signal }) => getApiWorkflowIdTransitions(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowIdTransitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>>
export type GetApiWorkflowIdTransitionsQueryError = unknown


export function useGetApiWorkflowIdTransitions<TData = Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdTransitions<TData = Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdTransitions<TData = Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get transitions of a workflow definition
 */

export function useGetApiWorkflowIdTransitions<TData = Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowIdTransitionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get transitions of a workflow definition
 */
export const prefetchGetApiWorkflowIdTransitionsQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowIdTransitions>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowIdTransitionsQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



