/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export interface AssignLeadDto {
  /** Sales nhận lead (bỏ trống nếu gán cho team) */
  salesId?: string;
  /** Team nhận lead */
  teamId?: string;
}
