/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export interface CreatePropertyContactDto {
  /** UUID of the Property record */
  propertyId: string;
  /** publicLinkCode từ URL ?ref= — BE resolve sang assignment → sales nhận contact. Không truyền recipientUserId trực tiếp. */
  refCode?: string;
  userName: string;
  userPhone: string;
  userContent?: string;
}
