/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export interface CreateTeamDto {
  /**
   * @minLength 1
   * @maxLength 150
   */
  name: string;
  /** User ID của trưởng nhóm (team leader) */
  leaderId: string;
  /** Danh sách user ID thêm vào team ngay khi tạo */
  memberIds?: string[];
}
