/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { CreateUserDtoGender } from './createUserDtoGender';

export interface CreateUserDto {
  fullName: string;
  email: string;
  /** Username đăng nhập — 3-30 ký tự (chữ, số, _, ., -) */
  username?: string;
  /** @minLength 8 */
  password: string;
  phone?: string;
  /** ISO date string (YYYY-MM-DD) */
  dateOfBirth?: string;
  gender?: CreateUserDtoGender;
  /** Location ID (province level, type=PROVINCE) — from /locations?type=PROVINCE */
  provinceId?: string;
  /** Location ID (ward level, type=WARD) — from /locations?type=WARD&parentId=<districtId> */
  wardId?: string;
  /** Tenant role IDs to assign — user is added to current tenant as member */
  roleIds?: string[];
}
