/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { CreateLeadDtoSource } from './createLeadDtoSource';
import type { CreateLeadDtoStatus } from './createLeadDtoStatus';
import type { CreateLeadDtoDynamicValuesJson } from './createLeadDtoDynamicValuesJson';
import type { CreateLeadDtoMetadata } from './createLeadDtoMetadata';

export interface CreateLeadDto {
  /** Auto-generated as LD-DDMMyy-NNN if omitted */
  leadCode?: string;
  customerId?: string;
  customerNeedId?: string;
  propertyId?: string;
  source: CreateLeadDtoSource;
  sourceUserId?: string;
  assignedSalesId?: string;
  phoneNormalized?: string;
  status?: CreateLeadDtoStatus;
  dynamicValuesJson?: CreateLeadDtoDynamicValuesJson;
  metadata?: CreateLeadDtoMetadata;
}
