/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type CreateMyNeedDtoPurpose = typeof CreateMyNeedDtoPurpose[keyof typeof CreateMyNeedDtoPurpose];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMyNeedDtoPurpose = {
  BUY: 'BUY',
  RENT: 'RENT',
  INVEST: 'INVEST',
  SELL: 'SELL',
  LEASE_OUT: 'LEASE_OUT',
} as const;
