/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { GetApiLeadsPoolStatus } from './getApiLeadsPoolStatus';

export type GetApiLeadsPoolParams = {
status?: GetApiLeadsPoolStatus;
search?: string;
limit?: string;
offset?: string;
};
