/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { GetApiLeadsStatus } from './getApiLeadsStatus';
import type { GetApiLeadsSource } from './getApiLeadsSource';

export type GetApiLeadsParams = {
status?: GetApiLeadsStatus;
source?: GetApiLeadsSource;
customerId?: string;
propertyId?: string;
search?: string;
limit?: string;
offset?: string;
};
