/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type GetApiTeamsStatus = typeof GetApiTeamsStatus[keyof typeof GetApiTeamsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiTeamsStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
