/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type GetApiWorkflowEntityStatusFieldsEntityType = typeof GetApiWorkflowEntityStatusFieldsEntityType[keyof typeof GetApiWorkflowEntityStatusFieldsEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiWorkflowEntityStatusFieldsEntityType = {
  PROPERTY: 'PROPERTY',
  LEAD: 'LEAD',
} as const;
