/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { GetApiLeadsAdminStatus } from './getApiLeadsAdminStatus';
import type { GetApiLeadsAdminSource } from './getApiLeadsAdminSource';

export type GetApiLeadsAdminParams = {
status?: GetApiLeadsAdminStatus;
source?: GetApiLeadsAdminSource;
customerId?: string;
propertyId?: string;
search?: string;
limit?: string;
offset?: string;
};
