/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { GetApiTeamsStatus } from './getApiTeamsStatus';

export type GetApiTeamsParams = {
/**
 * Tìm theo tên team
 */
search?: string;
status?: GetApiTeamsStatus;
limit?: number;
offset?: number;
};
