/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { RegisterDtoRoleCode } from './registerDtoRoleCode';
import type { RegisterDtoGender } from './registerDtoGender';

export interface RegisterDto {
  fullName: string;
  email: string;
  /** Username đăng nhập — 3-30 ký tự (chữ, số, _, ., -) */
  username?: string;
  /** @minLength 8 */
  password: string;
  /**
   * @minLength 10
   * @maxLength 20
   */
  phone: string;
  /** Role to assign on registration. Defaults to CUSTOMER. Allowed: CUSTOMER | OWNER | SALES */
  roleCode?: RegisterDtoRoleCode;
  /** ISO date string (YYYY-MM-DD) */
  dateOfBirth: string;
  gender?: RegisterDtoGender;
  /** Location ID (province level, type=PROVINCE) — from /locations?type=PROVINCE */
  provinceId?: string;
  /** Location ID (ward level, type=WARD) — from /locations?type=WARD&parentId=<districtId> */
  wardId?: string;
}
