/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { ReplaceUserDtoUsername } from './replaceUserDtoUsername';
import type { ReplaceUserDtoDateOfBirth } from './replaceUserDtoDateOfBirth';
import type { ReplaceUserDtoGender } from './replaceUserDtoGender';
import type { ReplaceUserDtoStatus } from './replaceUserDtoStatus';

export interface ReplaceUserDto {
  fullName: string;
  email: string;
  /** Username đăng nhập — bỏ trống sẽ reset về null */
  username?: ReplaceUserDtoUsername;
  /** @minLength 8 */
  password: string;
  phone?: string;
  /** File ID from uploaded avatar */
  avatarFileId?: string;
  /** ISO date string (YYYY-MM-DD) */
  dateOfBirth?: ReplaceUserDtoDateOfBirth;
  gender?: ReplaceUserDtoGender;
  /** Location ID (province level, type=PROVINCE) — from /locations?type=PROVINCE */
  provinceId?: string;
  /** Location ID (ward level, type=WARD) — from /locations?type=WARD&parentId=<districtId> */
  wardId?: string;
  status: ReplaceUserDtoStatus;
}
