/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

/**
 * Username đăng nhập — bỏ trống sẽ reset về null
 */
export type ReplaceUserDtoUsername = { [key: string]: unknown };
