/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { UpdatePropertyContactDtoStatus } from './updatePropertyContactDtoStatus';

export interface UpdatePropertyContactDto {
  status?: UpdatePropertyContactDtoStatus;
}
