/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { UpdateProfileDtoUsername } from './updateProfileDtoUsername';
import type { UpdateProfileDtoGender } from './updateProfileDtoGender';

export interface UpdateProfileDto {
  /**
   * @minLength 2
   * @maxLength 100
   */
  fullName: string;
  /** Username đăng nhập — null để xóa */
  username?: UpdateProfileDtoUsername;
  /**
   * @minLength 10
   * @maxLength 20
   */
  phone: string;
  /** File ID from uploaded avatar */
  avatarFileId?: string;
  /** ISO date string (YYYY-MM-DD) */
  dateOfBirth: string;
  gender?: UpdateProfileDtoGender;
  /** Location ID (province level, type=PROVINCE) — from /locations?type=PROVINCE */
  provinceId?: string;
  /** Location ID (ward level, type=WARD) — from /locations?type=WARD&parentId=<districtId> */
  wardId?: string;
}
