/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { UpdateDealDtoStatus } from './updateDealDtoStatus';
import type { UpdateDealDtoTransactionType } from './updateDealDtoTransactionType';
import type { UpdateDealDtoDynamicValuesJson } from './updateDealDtoDynamicValuesJson';

export interface UpdateDealDto {
  status?: UpdateDealDtoStatus;
  transactionType?: UpdateDealDtoTransactionType;
  currentWorkflowState?: string;
  salesUserId?: string;
  ownerUserId?: string;
  expectedValue?: string;
  finalValue?: string;
  dynamicValuesJson?: UpdateDealDtoDynamicValuesJson;
  metadata?: string;
}
