/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type UpdateDealDtoTransactionType = typeof UpdateDealDtoTransactionType[keyof typeof UpdateDealDtoTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateDealDtoTransactionType = {
  SALE: 'SALE',
  RENT: 'RENT',
  TRANSFER: 'TRANSFER',
} as const;
