/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type UpdatePropertyDtoSellingMode = typeof UpdatePropertyDtoSellingMode[keyof typeof UpdatePropertyDtoSellingMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePropertyDtoSellingMode = {
  SELF_SELL: 'SELF_SELL',
  SALES_DISTRIBUTION: 'SALES_DISTRIBUTION',
  HYBRID: 'HYBRID',
  INTERNAL_ONLY: 'INTERNAL_ONLY',
  MARKETPLACE_PUBLIC: 'MARKETPLACE_PUBLIC',
} as const;
