/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { UpdateLeadDtoStatus } from './updateLeadDtoStatus';
import type { UpdateLeadDtoDynamicValuesJson } from './updateLeadDtoDynamicValuesJson';
import type { UpdateLeadDtoMetadata } from './updateLeadDtoMetadata';

export interface UpdateLeadDto {
  status?: UpdateLeadDtoStatus;
  /** Team phụ trách */
  assignedTeamId?: string;
  /** Sales phụ trách */
  assignedSalesId?: string;
  phoneNormalized?: string;
  protectionUntil?: string;
  dynamicValuesJson?: UpdateLeadDtoDynamicValuesJson;
  metadata?: UpdateLeadDtoMetadata;
}
